### ISSUE TITLE
Github Pages not Updated.

### ISSUE THREAD

**Issue by itsrealkaran** [ZeroOctave/ZeroOctave-Javascript-Projects#1008]
I want to inform you that the github pages for the project is not updated as per the latest repository update. Just update the page for new contributors to get the proper idea of webapp.

**Comment by Adityasaini10012001** [comment]
assign this to me

**Comment by Anmol-Baranwal** [comment]
I assure you, it is working fine, and the projects are updated. 
e.g. You can see the stopwatch project updated merely hours ago.
