### ISSUE TITLE
Landing Page Enhancement

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#102]
You can Put landing page main files, index.html/style.css/script.js outside every folder and put every other things related to landing page inside assets.

for reference: https://github.com/Astrodevil/Awesome-JavaScript-Projects/blob/main/script.js 
make a script.js file like this for landing page so that any new contributors can easily link there projects to landing page.

You Can drop your suggestions too.. If you can make it more simple to add projects.

Others Things You can Enhance:
1. Add logo
2. Add some documentation
3. Make Landing Page more Attractive

**Comment by o0aman0o** [comment]
Assign me. I'll work on it

**Comment by Astrodevil** [comment]
Are you sure, You can make it more better? You can take your own time. No need to hurry.

**Comment by Astrodevil** [comment]
@o0aman0o Are you working on this?

**Comment by o0aman0o** [comment]
yeah please assign someone else....i am in too much burden right now.....sorry for inconvience

**Comment by o0aman0o** [comment]
@Astrodevil

**Comment by Astrodevil** [comment]
> 
> 
> Yes I'm working on it but I need 1 or 2 days to complete cause I was busy past days. I will update here for sure.

@ArijitAcharjee411 ??
