### ISSUE TITLE
Color-Quote

### ISSUE THREAD

**Issue by sulakshanachetry** [ZeroOctave/ZeroOctave-Javascript-Projects#1020]
**Is your feature request related to a problem? Please describe.**
A colour changer 

**Describe the solution you'd like**
A colour-changing quote

**Describe alternatives you've considered**
Use of HTML and CSS 

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Anmol-Baranwal** [comment]
@sulakshanachetry 
If you want to add this project with correct directory structure after reading the contributing guidelines. Feel free to make a new PR. 
For now, I am closing this issue.
