### ISSUE TITLE
Password Generator 

### ISSUE THREAD

**Issue by Swap-nil-2003** [ZeroOctave/ZeroOctave-Javascript-Projects#1023]
**Is your feature request related to a problem? Please describe.**
I would like to contribute a Password Generator App which would solve the problem of trying to create passwords for various important purposes such as creating an account. 

**Describe the solution you'd like**
The user will be allowed to input the no of characters they want along with other specifications such as with or without special characters. Accordingly, a random Password will be generated. 

**Describe alternatives you've considered**
Users can choose to customize the password as per their wish. 

**Additional context**
![Screenshot_20221104-153848](https://user-images.githubusercontent.com/93329536/199947660-4de9c3fe-4b69-438a-885d-ffeada6f1240.jpg)
![Screenshot_20221104-153926](https://user-images.githubusercontent.com/93329536/199947674-f5b667e0-642c-4b1c-9925-ba7a306c2fca.jpg)
![Screenshot_20221104-153937](https://user-images.githubusercontent.com/93329536/199947677-b7c06d05-0979-43c1-a0c7-0d11ee57195c.jpg)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Anmol-Baranwal** [comment]
You can reopen issue, if you want to add further functionalities to the existing password generator project.
