### ISSUE TITLE
Project Maintainer Needed

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#1037]
If anyone is Interested to maintain this project properly, I will give the collaborator access to that person. I will be busy in my college for next few months, I don't want the contribution made in this project to be wasted. If anyone wants to get into open source through maintaining this project properly, I am more than happy to welcome.🙏🏼

Goal should be to make **ZeroOctave-Javascript-Projects**  a project for beginners where they can contribute small projects and improve by practicing basic web development skills.

### Why you should maintain?
- Get familiar with project maintainer role and learn to review codes.
- Participate in open-source programs like GirlScript Summer of Code, DWoC and many more as maintainer or project Admin.
- Collaborate with fellow contributors.

### Expectation from you!
- Don't Change Project directory structure.
- Only accept project with HTML, CSS and JS (Not Js Frameworks)
- Maintain repository and review codes properly.
- Don't accept PRs of similar project instead ask contributors to improve existing ones.
- Website and README should be updated properly.

### Eligibility
- You must be familiar with Web Development technologies required for this repository.
- Working as contributor in the past for this repository will be good consideration.
- You should have knowledge or any prior experience of code reviews on Github.

**Note:** Beginners can also join if they feel they can get the work done.

**Comment by Shashanks0616** [comment]
Yes i am ready to maintain this projects

**Comment by Anmol-Baranwal** [comment]
What is the update. @Astrodevil 

Will you add me as a collaborator?

**Comment by Astrodevil** [comment]
> What is the update. @Astrodevil 
> 
> 
> 
> Will you add me as a collaborator?

Yes,for sure. Are you comfortable with the repo? I will also help you in managing sometimes.

Will also add 1,2 collaborators soon, as I can find any interested folks.

**Comment by Astrodevil** [comment]
> Yes i am ready to maintain this projects

Go through the repo once, tell me if you can manage it properly, so that I can give access to 2,3 folks as collaborator to make things easier.

**Comment by Astrodevil** [comment]
@Anmol-Baranwal Are you ready to maintain? Please confirm so that I can give you collaborator access.

**Comment by Anmol-Baranwal** [comment]
Yes, please give the collaborator access at the midnight. I want to see the repo once again for the clarifications.

**Comment by Astrodevil** [comment]
Yes we can update README and ask new contributors to update this and cards.json properly for each new project.

And for discord yes I have one discord channel but inactive, I will add you and others there.

**Comment by Astrodevil** [comment]
Join here: https://discord.gg/TH7hWD4Hqz @Anmol-Baranwal

**Comment by Emerald1996** [comment]
Yes I am very much interested and to maintain this project

**Comment by Nafiu29** [comment]
👋 Hello, I'm interested in managing the project, I just go through The source and I think am comfortable with it

**Comment by Astrodevil** [comment]
@Nafiu29 @Emerald1996 I would like you to review some PRs properly for this repo. So that I can get an overview of your maintainer skill.

**Comment by 357322** [comment]
I'm also interested

**Comment by William73920** [comment]
I'll be happy to take up this opportunity

**Comment by Astrodevil** [comment]
You can join us a mentor through GSSoC program. Apply here: https://gssoc.girlscript.tech/
