### ISSUE TITLE
Github pages not working properly

### ISSUE THREAD

**Issue by rafael-rodrigues01** [ZeroOctave/ZeroOctave-Javascript-Projects#1039]
![image](https://user-images.githubusercontent.com/106329803/217809957-c1c409d1-e582-4d86-aa78-126d8c894dad.png)

**Comment by Astrodevil** [comment]
Work on dark mode toggle, other cards are working fine now.

**Comment by DhirajGilda** [comment]
is this issue still open @Astrodevil  i would like to contribute

**Comment by Astrodevil** [comment]
Yes go ahead @DhirajGilda

**Comment by DhirajGilda** [comment]
Hi @Astrodevil 

I'm creating a light and dark theme for a these repository and I was wondering if you could share the HEX or RGB values for the primary, secondary, and accent colors you'd like me to use or should i just go ahead and make changes that i think will look good?

Thank you,

**Comment by DhirajGilda** [comment]
also github pages are working fine now @Astrodevil
