### ISSUE TITLE
Change Project Landing Page

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#1046]
### Concise Description

Change projects collection page UI in whole new way

### Solution Proposed

Change https://zerooctave.co/ZeroOctave-Javascript-Projects/ by taking reference from https://www.stackai.co/

### Sections Completed

- [x] Concise Description
- [x] Solution Proposed
- [ ] Alternative Solutions
- [ ] Additional-Context

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md) of this project.
- [X] I have checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have read the [readme](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md) of this repository.

**Comment by mud1tx** [comment]
@Astrodevil I can work on this issue easily. Please assign it to me.

**Comment by Astrodevil** [comment]
Go ahead @mud1tx

**Comment by mud1tx** [comment]
@William73920 working on it

**Comment by aravind-s1** [comment]
Can I work on this issue?

**Comment by karantec** [comment]
please assign me this issue

**Comment by wx-it** [comment]
I would like to work on this

**Comment by Mozibix** [comment]
if this issue have not been fix yet,  would love to work on this.

**Comment by Mozibix** [comment]
@Astrodevil please kindly check review my PR on this issue 
Thanks
