### ISSUE TITLE
🐛 [BUG] - <the image at the maze game project is not showing its broken>

### ISSUE THREAD

**Issue by Nitishupkr** [ZeroOctave/ZeroOctave-Javascript-Projects#1054]
### Description

the image at the maze game project is not showing its broken
![Screenshot 2023-06-04 184815](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/95420063/31c28d5c-fa33-4f32-a0db-41166720e5c4)

### Reproduction URL

https://zerooctave.co/ZeroOctave-Javascript-Projects/

### Reproduction steps

```bash
1. Go to 'https://zerooctave.co/ZeroOctave-Javascript-Projects/'
2. Scroll down to 'maze game'
3. See error
```

### Screenshots

```bash
![Screenshot 2023-06-04 184815](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/95420063/56511021-7cde-4c67-bc6c-462a819c8868)

```

### Sections Completed

- [X] Description
- [X] Reproduction URL
- [X] Reproduction steps
- [ ] Screenshots
- [ ] Logs
- [ ] Browsers
- [X] OS
- [ ] Additional Context

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md) of this project.
- [X] I have checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have read the [readme](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md) of this repository.

**Comment by aravind-s1** [comment]
can i work on it

**Comment by Nitishupkr** [comment]
I m already working on it today i will submit PR for this

**Comment by Nitishupkr** [comment]
Thanks for showing interest

**Comment by gopiexplore** [comment]
Hi i just fixed this and made a pr
