### ISSUE TITLE
🐛 [BUG] - <the image at the Range-Slider project is not showing its broken> 

### ISSUE THREAD

**Issue by gopiexplore** [ZeroOctave/ZeroOctave-Javascript-Projects#1059]
### Description

the image at the range-slider project is not showing its broken
![Screenshot (96)](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/125110272/fd06aef1-c5ca-4b2b-a075-d3df7de31fa6)

### Reproduction URL

https://zerooctave.co/ZeroOctave-Javascript-Projects/

### Reproduction steps

```bash
1. Go to 'https://zerooctave.co/ZeroOctave-Javascript-Projects/'
2. Scroll down to 'maze game'
3. See error
```

### Screenshots

```bash
![Screenshot (96)](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/125110272/fd06aef1-c5ca-4b2b-a075-d3df7de31fa6)
```

### Browsers

Chrome, Firefox, Microsoft Edge, Brave

### Sections Completed

- [X] Description
- [X] Reproduction URL
- [X] Reproduction steps
- [X] Screenshots
- [ ] Logs
- [ ] Browsers
- [ ] OS
- [ ] Additional Context

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md) of this project.
- [X] I have checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have read the [readme](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md) of this repository.

**Comment by shivam969619** [comment]
can i take this issue

**Comment by gopiexplore** [comment]
yes sure if you have any dought  i will help you if you want

**Comment by prakashAditya639** [comment]
@gopiexplore Can you please review my pr?

**Comment by prakashAditya639** [comment]
@Astrodevil @Anmol-Baranwal @akshatkhatri Can you please review my pr?
