### ISSUE TITLE
🐛 [BUG] - <title>The Image at the Tourist Website Project is not Showing its broken

### ISSUE THREAD

**Issue by gopiexplore** [ZeroOctave/ZeroOctave-Javascript-Projects#1063]
### Description

Here The Image is not showing in the card its broken
![Screenshot (99)](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/125110272/d5712836-ad10-44ec-af15-f8c9f32c2b52)

### Reproduction URL

https://zerooctave.co/ZeroOctave-Javascript-Projects/

### Reproduction steps

```bash
1. Go to 'https://zerooctave.co/ZeroOctave-Javascript-Projects/'
2. Scroll down to 'Tourist Website'
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/125110272/d5712836-ad10-44ec-af15-f8c9f32c2b52
```

### Browsers

Chrome, Firefox, Safari, Microsoft Edge, Brave

### OS

Windows

### Sections Completed

- [X] Description
- [X] Reproduction URL
- [X] Reproduction steps
- [X] Screenshots
- [X] Logs
- [X] Browsers
- [ ] OS
- [X] Additional Context

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md) of this project.
- [X] I have checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have read the [readme](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md) of this repository.

**Comment by BlackBond06** [comment]
Hi @gopiexplore, I would love to resolve this issue, please assign it to me.

**Comment by prakashAditya639** [comment]
Please merge with Hacktoberfest-accepted
