### ISSUE TITLE
🐛 [BUG] - <dark-mode >

### ISSUE THREAD

**Issue by mohitmk007** [ZeroOctave/ZeroOctave-Javascript-Projects#1065]
### Description

after enable dark mode most of the content looking in white color which is not good for great website.

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
5.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
no
```

### Logs

```bash
no
```

### Additional Context

```bash
no
```

### Sections Completed

- [ ] Description
- [X] Reproduction URL
- [X] Reproduction steps
- [X] Screenshots
- [ ] Logs
- [ ] Browsers
- [ ] OS
- [ ] Additional Context

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md) of this project.
- [ ] I have checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ ] I have read the [readme](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md) of this repository.

**Comment by JD-3002** [comment]
Hey can you assign this issue to me?
