### ISSUE TITLE
💡 [REQUEST] - Improved UI and other changes for calculator

### ISSUE THREAD

**Issue by deveshidwivedi** [ZeroOctave/ZeroOctave-Javascript-Projects#1070]
### Concise Description

The thumbnail image for calculator is not at all related to the purpose it exists for, it could be changed. Also, UI is very basic, background consists of only a gradient and looks dull.

### Solution Proposed

- For the thumbnail image, I'd put up a better picture of a calculator, so that users do not get confused.
- To improve UI, I'm planning to change the background and color scheme, trying to make it more fun.

### Sections Completed

- [X] Concise Description
- [X] Solution Proposed
- [ ] Alternative Solutions
- [ ] Additional-Context

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md) of this project.
- [X] I have checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have read the [readme](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md) of this repository.

**Comment by sarcaxticlarka** [comment]
i want to work on this please assign me this project to improve ui and other changes

**Comment by Ankuristic** [comment]
could i work on the task of the UI of the calculator could you please assign this for me
