### ISSUE TITLE
Add your Web dev projects 

### ISSUE THREAD

**Issue by NOiR-07** [ZeroOctave/ZeroOctave-Javascript-Projects#11]
Hey! Welcome to our repo, here you can contribute by adding your projects or by contributing to existing projects

While adding new projects make sure to check the pattern followed in the repo for HTML, CSS and JS files.

For e.g
Html files should be added in public folder with name <Project-name>.html
CSS files should be added in assets/css with name <Project-name>.css
JS files should be added in assets/Js with name <Project-name>.js (If available)

Make sure to attach a gif/ss showcasing your project

**Create a new issue for adding projects**

**Comment by juhiechandra** [comment]
Should I attach a demo of the project in form of ss before make a PR?

**Comment by NOiR-07** [comment]
> Should I attach a demo of the project in form of ss before make a PR?

Yes sure, you can

**Comment by Astrodevil** [comment]
> 
> 
> Should I attach a demo of the project in form of ss before make a PR?

yes, that will be good, a ss or gif anything. Hactoberfest PR after

**Comment by NOiR-07** [comment]
> Should I attach a demo of the project in form of ss before make a PR?

Yes sure, if u want u can add a ss or gif of the project

**Comment by devanshtivari** [comment]
I think I have some wonderful ideas to contribute to your repo.

**Comment by NOiR-07** [comment]
> I think I have some wonderful ideas to contribute to your repo.

You are welcomed, go ahead👍

**Comment by Anubhav-1020** [comment]
Hey @NOiR-07 Can i add my web dev project to this repo. I am new to open source...this would be very helpful for me : )

**Comment by Astrodevil** [comment]
> Hey @NOiR-07 Can i add my web dev project to this repo. I am new to open source...this would be very helpful for me : )

Yes!🚀 Add your projects. Follow proper file structures of this repository.

**Comment by Prajakta102** [comment]
I think I have some wonderful ideas to contribute to your repo.
Please assign this task to me

**Comment by Astrodevil** [comment]
> 
> 
> I think I have some wonderful ideas to contribute to your repo. Please assign this task to me

@Prajakta102 Raise new issue and provide details like screenshot.

**Comment by juhiechandra** [comment]
![image](https://user-images.githubusercontent.com/75068056/135518728-784a33ca-262d-4dd6-b607-bdc251701550.png)
Here is visual view to #35

**Comment by shreya024** [comment]
Hi @NOiR-07 ,I would like to add a Star-Catching-Game coded in html,css and js.Please assign this task to me.

**Comment by NOiR-07** [comment]
> Hi @NOiR-07 ,I would like to add a Star-Catching-Game coded in html,css and js.Please assign this task to me.

You have been assigned

**Comment by singlapriyanka315** [comment]
hey @NOiR-07, I would like to add my web mini-project to this repo.

**Comment by NOiR-07** [comment]
> hey @NOiR-07, I would like to add my web mini-project to this repo.

Create a new issue, I'll assign you
