### ISSUE TITLE
Application Form

### ISSUE THREAD

**Issue by NEWCODECITY** [ZeroOctave/ZeroOctave-Javascript-Projects#117]
This is an Application Form , made with the help of HTML and CSS. 
You can use this , when you want a quick ,yet an effective Form with features that lets you insert any file from your system and all the other features , required to create a good Application Form.

**Comment by Harryagarwal** [comment]
Assign me the task !

**Comment by Astrodevil** [comment]
> 
> 
> Assign me the task !
