### ISSUE TITLE
I wish to add a Hulu clone to projects

### ISSUE THREAD

**Issue by arsheelsheikh** [ZeroOctave/ZeroOctave-Javascript-Projects#118]
I wish to add a Hulu clone to projects under Hacktoberfest 2021

<img width="1440" alt="Screenshot 2021-10-11 at 5 31 32 PM" src="https://user-images.githubusercontent.com/69401139/136787253-24f1959f-a1e5-4b01-9d3e-7c5ddade4e85.png">

**Comment by Astrodevil** [comment]
Go ahead! @arsheelsheikh
