### ISSUE TITLE
Documentation needed 

### ISSUE THREAD

**Issue by NOiR-07** [ZeroOctave/ZeroOctave-Javascript-Projects#12]
Edit the readme, contribution or any other file if u think some improvements can be done.
You can add any missing files too if u find

*Don't submit useless PR or issue, else you would be marked as spam/Invalid*

**Comment by devanshtivari** [comment]
I think I can edit the readme and can contribute in some other fields. So assign me this task.

**Comment by Astrodevil** [comment]
Go ahead @devanshtivari

**Comment by Astrodevil** [comment]
#15
