### ISSUE TITLE
landing page for this project

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#13]
A landing page where all projects from this repository can be showcased will be good.

*Suggestions Welcomed*

**Comment by SO1ee** [comment]
Hello sir! please assign me this task . I will design a responsive landing page(index.html) on which your every project (Analog_clock, Auto-write-text, calculator...... weather_app) will be showcased and on click individual page will come up . Thank you for your time.

**Comment by Prajakta102** [comment]
Please sir  assign this task to me as I have good understanding of front end skills even I made may projects using html ,css ,js .

**Comment by Astrodevil** [comment]
> 
> 
> Please sir assign this task to me as I have good understanding of front end skills even I made may projects using html ,css ,js .

As this task is already assigned, You can do some other work in this repo till then. Raise new issue

**Comment by SO1ee** [comment]
Hello sir! kindly have a look on our landing page and let me know if there any correction needed.
![Screenshot 2021-09-30 234701](https://user-images.githubusercontent.com/90699287/135510252-0b5dd2f6-a2b0-4e65-90c7-cc4ca28341c5.png)

**Comment by Astrodevil** [comment]
@SO1ee Good Work🚀 if possible can you add gif or images by running projects in every project card?

**Comment by SO1ee** [comment]
Sorry sir i didn't get it could you please explain it more.

**Comment by SO1ee** [comment]
Okay i have  understood what to do .

**Comment by SO1ee** [comment]
Hello sir as you have said to add individual javascript project on every card ,i have done that .So now the advantage is visitor don't need to click on every card to visit that project , at a glimpse on the landing page he/she can have an overall idea about every javascript project .Kindly have a look on this 
![Screenshot 2021-10-01 213741](https://user-images.githubusercontent.com/90699287/135653894-7561e46a-f957-428b-a964-53708a249fea.png)

**Comment by Astrodevil** [comment]
Nice work
