### ISSUE TITLE
Landing Page Enhancement🎉

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#138]
- Suggest and make some changes to the project [Landing Page.](https://zerooctave.github.io/ZeroOctave-Javascript-Projects/)
- Make it easy to add new projects on the landing page for new contributors.
- You can also build it from scratch

**Comment by Karan-Dhingra** [comment]
Sir, I have updated the landing page. You can review it here.
#150

**Comment by sabin-baniya** [comment]
Hey i can help with making landing page using react if you would like?

**Comment by Astrodevil** [comment]
@sabin-baniya   This project is focused on beginners, So please don't use react.

**Comment by Shivam-Katare** [comment]
Hi! @Astrodevil I do some changes in the weather and dice project so, you can check that one too.

**Comment by sahooniyatee** [comment]
hello! can u please assign me this issue  :)
@Astrodevil

**Comment by Astrodevil** [comment]
@sahooniyatee Go ahead

**Comment by ishika1501** [comment]
hello sir , i wanted to take this work , as i feel quite confident over m Ux/Ui skills and i am very much interested in frontend dev , please assign it to me .

**Comment by harshitab07** [comment]
Hey, @Astrodevil , Hey, I'm GSSOC'22 participant. I checked out the landing page and I find the heart animation quite inconsistent, also in my opinion it would look prettier if we could just adjust the opacity of hearts. I would like to make the UI of landing page more attractive. Kindly, assign this issue to me.
Thank You

**Comment by rashi1405** [comment]
hello , I am a participant of GSSOC'22 , can you assign me this project to work .

**Comment by Astrodevil** [comment]
Someone is working on this issue, I have to wait for the PR. 

I am not assigning this issue for now, but you can raise a new issue regarding the landing page with a new suggestion and if you want to make a landing page from **scratch**.

The landing page is so much inconsistent. It must contain all projects from the repository. **Make it easy to add new projects on the landing page for new contributors.** 

Project [Landing Page.](https://zerooctave.github.io/ZeroOctave-Javascript-Projects/)

**Comment by Astrodevil** [comment]
#201 Assigned
