### ISSUE TITLE
Want to join the organisation 😀

### ISSUE THREAD

**Issue by Palaksharma23** [ZeroOctave/ZeroOctave-Javascript-Projects#160]

**Comment by Astrodevil** [comment]
@Palaksharma23 Raise a Issue [here](https://github.com/ZeroOctave/ZeroOctave.github.io/issues/new?assignees=&labels=Invite+me+to+Zerooctave&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization) to join ZeroOctave
