### ISSUE TITLE
calculator application not opening

### ISSUE THREAD

**Issue by siva-krish45** [ZeroOctave/ZeroOctave-Javascript-Projects#171]
**Describe the bug**
In the landing page when we click the TRY NOW button on calculator app, it shows 404 error file not found.

**To Reproduce**
1. Go to https://zerooctave.github.io/ZeroOctave-Javascript-Projects/
2. Click on **try now** button on calculator application(https://zerooctave.github.io/ZeroOctave-Javascript-Projects/Public/calculator.html)
3. u can see the error of 404 file not found.

**Expected behavior**
when we click the button it should show the calculator application UI like this
![image](https://user-images.githubusercontent.com/69798791/155997513-d8a5b32e-2382-4f57-955b-a39810369f65.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/69798791/155997326-f55870fc-233e-4294-a626-8c79623c7897.png)

**Desktop (please complete the following information):**
 - Browser- chrome
 - Version -98

**Smartphone (please complete the following information):**

**Additional context**

**Comment by siva-krish45** [comment]
i am a gssoc'22 contributor . can u plzz assign me this issue ?

**Comment by Parth-Shete** [comment]
I am a GSSOC 22 contributor, would like to work on this issue, please assign me this issue. Do let me know what all things I need to keep in mind before starting my contribution.
