### ISSUE TITLE
Roman Numeral Converter

### ISSUE THREAD

**Issue by abhi1e9-1e10** [ZeroOctave/ZeroOctave-Javascript-Projects#172]
The main objective of this project is to convert  Arabic  numbers to Roman numerals or vice-versa.

Key concepts covered :-
1.) document.getElementById()
2.) event Listeners
3.) arabicToRoman()
4.) romanToArabic()
5.) objects
6.) for loop
7.) Math.floor()
8.) indexOf()
9.) replace()

**Comment by ShrutiKapure** [comment]
I am a GSSOC'22 participant, I want to work on this issue

**Comment by NOiR-07** [comment]
Any updates?? should i assign someone else or close this issue

**Comment by abhi1e9-1e10** [comment]
Sorry Sir I am busy in viva preparation I would  like to work on this issue after 14th march If you agree with me or  assign these issue to anybody...!!
Thank you Sir ....

**Comment by NOiR-07** [comment]
> Sorry Sir I am busy in viva preparation I would like to work on this issue after 14th march If you agree with me or assign these issue to anybody...!! Thank you Sir ....

no issues take ur time
