### ISSUE TITLE
 Mobile Number Validator

### ISSUE THREAD

**Issue by abhi1e9-1e10** [ZeroOctave/ZeroOctave-Javascript-Projects#173]
This project lets you find out if the mobile number you have entered is active and able to receive calls or not.
Key concepts covered :-
1.) document.querySelector()
2.) test()
3.) forEach()
4.) DOM manipulation
5.) event Listeners
6.) innerHTML

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903
