### ISSUE TITLE
add anime Profile pic generator to the Project list...

### ISSUE THREAD

**Issue by AmolShelke2** [ZeroOctave/ZeroOctave-Javascript-Projects#174]
Hey, Project Admin I'm GSSOC 2022 Participant and I've come up with your project I found it very comfortable with my coding tech stack so I want to add a Random anime profile pic generator to the ZeroOctave JavaScrit Projects Repository I hope you will go through my Issue and assign me the issue to work on it. I am attaching the Demo of the project please give it a look.

https://user-images.githubusercontent.com/95171638/156023847-5e90e71c-2b84-459d-aaf9-02636c29e4af.mp4

**Comment by Prajwal-ctrl** [comment]
hey @AmolShelke2  I am a gssoc'22 participant can work on it .

**Comment by AmolShelke2** [comment]
> hey @AmolShelke2 I am a gssoc'22 participant can work on it .

bro, it is my project I'm trying to add this project to their lists that's why I create the issue it is not for working on it..

**Comment by Prajwal-ctrl** [comment]
oops sorry

**Comment by AmolShelke2** [comment]
> oops sorry

don't worry bro tomorrow there will be a workshop for everyone who is a beginner in open-source so please attend that workshop it will teach you everything that you need to know for contributing to any projects [https://youtu.be/lUFAUWCk_4k]

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903
