### ISSUE TITLE
UI - enhancement in check_weather_app 

### ISSUE THREAD

**Issue by ABHID10** [ZeroOctave/ZeroOctave-Javascript-Projects#175]
**Enhancing UI** :
 1. Changing Search-bar.
 2. Adding card layout.
 3. Adding dynamic background which changes after every refresh.

GSSOC - 22

**Comment by ABHID10** [comment]
@NOiR-07 
#236 Please review these changes 
Couldn't understand conflict? 🤔 
Please help 🙏 !!

**Comment by Astrodevil** [comment]
No need to tag, we get notifications. You have to solve the conflict by removing some duplicate lines of code by checking this in your code editor. in your case may be 1st line is creating conflict.
