### ISSUE TITLE
To add rock paper scissors game

### ISSUE THREAD

**Issue by nitishsaini706** [ZeroOctave/ZeroOctave-Javascript-Projects#177]
Simple Js game to showcase the power of DOM in js using various js functions
**Concepts Userd**
1. Document.get.ElementById();
2. add event listner
3. arrow functions 
4. dom
5. innerHTML

**Comment by Aayush987** [comment]
Plz assign it to me.

**Comment by nitishsaini706** [comment]
@Aayush987  I raised this issue to work on it

**Comment by Aayush987** [comment]
> @Aayush987  I raised this issue to work on it 

I am so sorry. I didn't know about it.

**Comment by NOiR-07** [comment]
@nitishsaini706 already the same project lies in the repository so try to improve that if possible.
Closing this issue
