### ISSUE TITLE
new design to login form

### ISSUE THREAD

**Issue by LegendSumeet** [ZeroOctave/ZeroOctave-Javascript-Projects#179]
**Is your feature request related to a problem? Please describe.**
no, it's about to enhance the look of a login form

**Describe the solution you'd like**
new design to login form

**Describe alternatives you've considered**
adding more colors and new looks of the way

**Additional context**
background change and font

**Comment by TushitaParashar** [comment]
Hey can you assign this issue to me

**Comment by Sanghu01** [comment]
I want to work on this project.
