### ISSUE TITLE
A Speech Recognition Program using JavaScript

### ISSUE THREAD

**Issue by Aayush987** [ZeroOctave/ZeroOctave-Javascript-Projects#180]
A good looking speech recognition project that records whatever we say and turn it to text and display us. Good project with html,css and javascript

Additional Information-
 Issue created under the contributions of             GSSOC'22

**Comment by Aayush987** [comment]
I want to work on this too.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Aayush987** [comment]
@sceary-expert Hi actually I have created this issue to work on it. I have already made pr for the same.
