### ISSUE TITLE
Want to add a beginner friendly Js project incrementinator 2.0 with a nice UI using CSS Flexbox

### ISSUE THREAD

**Issue by prat1k-gupta** [ZeroOctave/ZeroOctave-Javascript-Projects#186]
**Is your feature request related to a problem? Please describe.**
No, It's just a beginner friendly JS project with a nice UI using CSS flex box.

It uses:
- functions() (function to increment  and reset)
- DOM 
- document.getElementById() ( to get element using id )
- innertext ( to change the text )

**Languages Used**
- HTML
- CSS (flexbox)
- Js

**Live Link**
https://prat1k-gupta.github.io/incrementinator2.0/

**Additional context**
- Screenshot of the project 
![image](https://user-images.githubusercontent.com/92115707/156116846-d6067ce3-cf89-488f-8119-eb2d5df2b2f7.png)

**Comment by prat1k-gupta** [comment]
completed this issue please check my PR

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903
