### ISSUE TITLE
Add a Candy Crush Clone

### ISSUE THREAD

**Issue by Adit0507** [ZeroOctave/ZeroOctave-Javascript-Projects#191]
**Project Description**
- This game can be operated using the mouse only.
- Beginners can learn the application of forEach() method
- Live Demo: https://adit0507.github.io/Candy-Crush/
**Describe the solution you'd like**

![Candy-Crush](https://user-images.githubusercontent.com/78037846/156125840-5fb435a4-91a8-4645-b4f4-b3f2f7a421d2.PNG)

**Comment by Adit0507** [comment]
I'm a GSSoC''22 participant

**Comment by NOiR-07** [comment]
@Adit0507 as I've seen you've raised issues for multiple projects so, I would suggest you to make a single pr and commit all projects in that, also mention all issue numbers for confirmation.

**Comment by Adit0507** [comment]
Sure
