### ISSUE TITLE
I want to add a javascript project , in which on typing the name of the color , the color of the UI changes to that color.

### ISSUE THREAD

**Issue by srinjoy-26** [ZeroOctave/ZeroOctave-Javascript-Projects#193]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by srinjoy-26** [comment]
Sir please assign this project to me.

**Comment by srinjoy-26** [comment]
PROJECT DESCRIPTION:
*Project is based on simple js functions.
*here the color changes according to the input color.
*try it out here - https://srinjoy-26.github.io/UI-color-changer/

**Comment by NOiR-07** [comment]
A similar project already exists.
