### ISSUE TITLE
Birthday Card

### ISSUE THREAD

**Issue by Anchita15** [ZeroOctave/ZeroOctave-Javascript-Projects#196]
I have made this birthday card using CSS; HTML; JavaScript. It has an birthday audio too as soon as you open the card. I hope you'll like it :)
Live : https://anchita15.github.io/BirthdayCard/
<img width="931" alt="Screenshot 2022-03-01 144936" src="https://user-images.githubusercontent.com/83870242/156142687-b9b7ad41-e332-49ca-98fc-7289cf50d9f4.png">
<img width="941" alt="Screenshot 2022-03-01 144958" src="https://user-images.githubusercontent.com/83870242/156142696-f5e111b7-11ee-4043-b20f-94cb0dd3adf5.png">

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Anchita15** [comment]
> I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

I am almost completed with the issue. You can raise some other issue. Thank you!

**Comment by pushpanjali-10** [comment]
Hi, I am a GSSOC Contributor and I would like to work on this issue. please assign this issue to me.

**Comment by Anchita15** [comment]
> Hi, I am a GSSOC Contributor and I would like to work on this issue. please assign this issue to me.

I am already working on this issue

**Comment by ishashukla183** [comment]
i would like to work on this issue if it's open
