### ISSUE TITLE
Add URL SHRINKER APP Under GSSOC`22

### ISSUE THREAD

**Issue by Gurdeep475** [ZeroOctave/ZeroOctave-Javascript-Projects#197]
# I want to add a Url shrinker app

- It Converts long URLs into Short
- It saves the URL's into the database
- it remembers the no of times the Short URL was clicked.

**Comment by Gurdeep475** [comment]
I want my url shrinker project to be the part of this project, that's why i added this issue. Please assign it to me under GSSOC`22.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Gurdeep475** [comment]
@sceary-expert I am already working on this issue.

**Comment by NOiR-07** [comment]
Any updates?? should i assign someone else or close this issue

**Comment by Gurdeep475** [comment]
Yes, it's almost complete, I will make PR by Today.

**Comment by NOiR-07** [comment]
> Yes, it's almost complete, I will make PR by Today.

okay

**Comment by Gurdeep475** [comment]
@NOiR-07 the project is in Javascript and Node.js will it be ok?

**Comment by NOiR-07** [comment]
@Astrodevil pls confirm

**Comment by Gurdeep475** [comment]
and i have deployed it already and can create a html page in this project, that redirects to that deployed link.

**Comment by Gurdeep475** [comment]
@NOiR-07 any updates?
