### ISSUE TITLE
Landing page from scratch

### ISSUE THREAD

**Issue by harshitab07** [ZeroOctave/ZeroOctave-Javascript-Projects#201]
**Is your feature request related to a problem? Please describe.**
The landing page is way too inconsistent due to different size of the UI of different projects.

**Describe the solution you'd like**
Rather than placing projects in a flex box it would look better if for desktop and tablet version we could add apps in a back and forth slider and for mobile version we can use flex box as it won't cause inconsistency in small screens.

Kindly assign me this issue ( also please let me know if bootstrap can be used )

**Comment by Astrodevil** [comment]
Yes bootstrap & tailwind can be used, Only thing to consider is to make code base of landing page very simple so that any new contributor can also list their project on landing page by themselves. Put html,css,js codes in separate files if needed. 

Are you contributing for gssoc22?

**Comment by harshitab07** [comment]
@Astrodevil  Yes I'm contributing for GSSoC'22
