### ISSUE TITLE
Want to add an animated login page

### ISSUE THREAD

**Issue by Kalyani02072003** [ZeroOctave/ZeroOctave-Javascript-Projects#210]
**Is your feature request related to a problem? Please describe.**
An animated login and sign up page

**Additional context**
![Screenshot (304)](https://user-images.githubusercontent.com/71889838/156222670-a5ffef94-6d27-4311-a7fd-9623b30f1c62.png)
![Screenshot (305)](https://user-images.githubusercontent.com/71889838/156222795-73fe0a34-b129-4cfa-90cf-e0f4a71819cd.png)

**Comment by NOiR-07** [comment]
similar project already exists
