### ISSUE TITLE
docs: Add PR template

### ISSUE THREAD

**Issue by Pradumnasaraf** [ZeroOctave/ZeroOctave-Javascript-Projects#211]
### Chnages 
- Adding a PR template
- Template path **`.github/PULL_REQUEST_TEMPLATE.md`**

### Template Preview (while creating a PR.)
![Screenshot from 2022-03-01 17-54-32](https://user-images.githubusercontent.com/51878265/156168840-66822d65-3e60-4026-8064-f967d66cf94b.png)

####  Due to that we are also missing out on some checks on the community standards checklist

![Screenshot from 2022-03-01 23-49-05](https://user-images.githubusercontent.com/51878265/156226212-90bb93fa-df8e-4484-8c9d-9da692389980.png)

**Comment by Astrodevil** [comment]
Try to make it more customized to this project.
