### ISSUE TITLE
Joke Generator (Chrome Extension)

### ISSUE THREAD

**Issue by Atharv-110** [ZeroOctave/ZeroOctave-Javascript-Projects#213]
<i>Sometimes a coder gets bored of coding or it gets heavy for him to carry out the rest of the coding. So, he needs a break where he do not wanna touch his phone ir open up any social handles. What could make his mood fresh?</i>

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Atharv-110** [comment]
@sceary-expert bro this is assigned to me please refer to the another project and this issue was raised by me first and it will be FCFS.

**Comment by Atharv-110** [comment]
Hey @NOiR-07, I have raised my PR. Please do review it.
