### ISSUE TITLE
Wordle Game

### ISSUE THREAD

**Issue by Pragati1122** [ZeroOctave/ZeroOctave-Javascript-Projects#220]
Project title
Wordle Clone

Project Description
Wordle is a simple word guessing game popular across the world. You have six chances to guess the day's secret five-letter word. Type in a word as a guess, and the game tells you which letters are or aren't in the word. If you guess the right letter but in the wrong spot, it turns yellow and if you guess the right letter in the right spot, it turns green. The aim is to figure out the secret word with the fewest guesses.

I will also use an API to pull in a new word to guess and also to check that the guessed word is a real word.

I have also attached a snapshot for reference to the game.

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

![image](https://user-images.githubusercontent.com/84949697/156317142-34791e99-669d-45bb-9827-32565922fa90.png)

**Comment by Pragati1122** [comment]
I want to work on this as a participant of GSSoC22, please assign me this. @Astrodevil

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Pragati1122** [comment]
> Any updates?? should i assign someone else or close this issue

I am working on it, will open a PR as soon as it is completed.

**Comment by NOiR-07** [comment]
> > Any updates?? should i assign someone else or close this issue
> 
> I am working on it, will open a PR as soon as it is completed.

sure

**Comment by Sulagna-Dutta-Roy** [comment]
If no pull requests here. Can I work on this Issue ??? @Astrodevil
