### ISSUE TITLE
Add a color code converter JS app

### ISSUE THREAD

**Issue by XZANATOL** [ZeroOctave/ZeroOctave-Javascript-Projects#223]
**Is your feature request related to a problem? Please describe.**

It's a JS app that converts from and to different color representation codes like RGB, Hex, HSL, HWB, CMYK, ..etc.

**Additional context**

Gonna make use of HTML, CSS, & JS.

### Steps Followed✅

- [x] Is your feature request related to a problem? Please describe.
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by SonikeshKumar14** [comment]
Hi! I would like to work on this issue under GSSOC`22. Please assign it to me.

**Comment by sreelakshmig009** [comment]
Hi sorry these projects already exist. You can create a new issue with any feature improvisation or contribute a new proejct which isnt already there

**Comment by XZANATOL** [comment]
@sreelakshmig009 I think there is some kind of miss-understanding (maybe from my side) but I can't find a similar converter on the repository. There are only color flippers that generates random colors, while my proposal is about a calculator-like JS app that converts between color codes like this one on [w3schools](https://www.w3schools.com/colors/colors_converter.asp).

So is a double checking is available considering this issue?

**Comment by sreelakshmig009** [comment]
> @sreelakshmig009 I think there is some kind of miss-understanding (maybe from my side) but I can't find a similar converter on the repository. There are only color flippers that generates random colors, while my proposal is about a calculator-like JS app that converts between color codes like this one on [w3schools](https://www.w3schools.com/colors/colors_converter.asp).
> 
> So is a double checking is available considering this issue? and if there is another converter on the repo can you point it out here?

I'll reopen this issue because as you guessed I thought it was similar to a color flipper. Do attach a video of the project while creating a pr
