### ISSUE TITLE
Add a  Dice Game Project

### ISSUE THREAD

**Issue by yashikhare** [ZeroOctave/ZeroOctave-Javascript-Projects#225]
I want to add a Dice Game Project using HTML, CSS, and JavaScript. 
The Dice Game is based on a two-player. Both players roll the dice and the player who gets the highest phase value will win the game.
I am a GSSOC'22 participant and  I want to work on this issue.
can you please assign this issue to me?

**Comment by ronitrangwani** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by Astrodevil** [comment]
It's already exists
