### ISSUE TITLE
improve UI/UX of Cards and box in website.

### ISSUE THREAD

**Issue by SayedTabish72** [ZeroOctave/ZeroOctave-Javascript-Projects#227]
##Is your feature request related to a problem? Please describe.**
 🙋‍♂️𝗛𝗶 [ZeroOctave](https://github.com/ZeroOctave), If, you have assign me for the contributing on this issue. **To improve UI/UX of Cards and box in website.**
## Example:
https://user-images.githubusercontent.com/93794214/156365981-589af417-1532-4563-8762-9e0afc4a0b79.mp4
### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by bhavyapathak20** [comment]
@Astrodevil 

I would like to work on this issue.
My Skills in web development :

1)HTML
2)CSS
3)Bootstrap
4)Javascript
5)Jquery

My experience :
5+ months of experience in UI design.
Worked on Hands-on projects. My Github repo shows it

**Comment by sreelakshmig009** [comment]
@Astrodevil

**Comment by Astrodevil** [comment]
@SayedTabish72 You are proposing changes on landing page?

**Comment by Burrito1510** [comment]
@Astrodevil I believe the issue hasn't been assigned yet, and the landing page needs a lot of alterations with respect to the UI. I'd like to work on this issue, having previous experience with design.
