### ISSUE TITLE
Add a Custom Ice Cream Maker

### ISSUE THREAD

**Issue by Adit0507** [ZeroOctave/ZeroOctave-Javascript-Projects#230]
**Custom Ice Cream Maker**
In this project the user can customize the flavor (color) of the ice cream and also play around with the toppings.

**Describe the solution you'd like**

![Ice-Cream](https://user-images.githubusercontent.com/78037846/156380489-3209bdcb-4184-4d73-bf5d-a6bbb2c33ca7.PNG)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Adit0507** [comment]
I dont know why the duplicate label is added in this issue, because I can't see any other issue mentioning this project.

**Comment by AnweshaRoses** [comment]
We can have different flavors names and the user can only choose 3 scoops per Ice cream and they try to choose more we can show them an alert and after that we can have few toppings and they will get layered on top of each other and this can be implemented by creating a checkbox kind of thing so the user will understand that they can select and unselect the toppings

**Comment by AnweshaRoses** [comment]
If you think the Idea is good then please assign it to me, I would love to work on it.

Thank you.
