### ISSUE TITLE
Want to add a Drum Kit Project

### ISSUE THREAD

**Issue by VIPIN-creator** [ZeroOctave/ZeroOctave-Javascript-Projects#231]
![image](https://user-images.githubusercontent.com/59695863/156381936-b08aab94-f868-49d4-80ea-7ad967d97eec.png)

I want to add this project under GSSOC'22. 
Have a look into it.
https://vipin-creator.github.io/Drum-Kit/

**Comment by Astrodevil** [comment]
It already exists. Feel free to raise another issue.
