### ISSUE TITLE
Adding a navbar and a footer 

### ISSUE THREAD

**Issue by Rhydham2809** [ZeroOctave/ZeroOctave-Javascript-Projects#237]
I can add a navbar and a footer to this beautiful website.
I am Gssoc 2022 participate.
Kindly assign this issue to me.

**Comment by RajatBhaskare7** [comment]
assign me this task

**Comment by SamarthKavathe** [comment]
can you please assign me this issue

**Comment by sreelakshmig009** [comment]
@RajatBhaskare7 @SamarthKavathe feel free to create new issues

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by NOiR-07** [comment]
Any updates?? should i assign someone else or close this issue

**Comment by Rhydham2809** [comment]
Hello,
Yes I am working on this issue and it is almost ready, shortly I will pull a merge request and sorry  for such delay.

**Comment by NOiR-07** [comment]
> Hello, Yes I am working on this issue and it is almost ready, shortly I will pull a merge request and sorry for such delay.

no issues

**Comment by pushpanjali-10** [comment]
I am GSSoc 2022 participate.
Kindly assign this issue to me.
