### ISSUE TITLE
Add Age Predictor to the projects

### ISSUE THREAD

**Issue by vardhinii** [ZeroOctave/ZeroOctave-Javascript-Projects#238]
**Describe the Project**
The project is a web app that predicts the age of the person based on their name. Naming styles have been constantly changing with growing years, this project, analyses the name and gives their predicted age (approximate age based on name). It also has features to predict age along with nationality. 

**Tech Stacks to be used**
HTML, CSS, Javascript and API

**Additional context**
This what workflow look like:
+ Enter your name
+ Enter your nationality
+ Output of age

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by vardhinii** [comment]
Please assign this task to me and I don't know why it has label of duplicate

**Comment by NOiR-07** [comment]
Any updates?? should i assign someone else or close this issue
