### ISSUE TITLE
Memory game

### ISSUE THREAD

**Issue by Madhumitha155** [ZeroOctave/ZeroOctave-Javascript-Projects#239]
I would like to add a memory game built using HTML,CSS,JS. I am a GSSOC22 participant

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Madhumitha155** [comment]
I am a GSSOC participant and want to build the memory game.Pls assign me

**Comment by Madhumitha155** [comment]
There is a duplicate label but there is no other issue being made with the same project.

**Comment by NOiR-07** [comment]
Any updates?? should i assign someone else or close this issue

**Comment by Madhumitha155** [comment]
I am working on it will make the pull request within two days
