### ISSUE TITLE
Projects on landing page

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#240]
Add remaining projects from this repository to landing page. This can be done in index.html file. Take screenshot by running projects in local machine & use it as images for landing page project preview. Follow proper order and add comments for every project. 

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by ShamithaReddy** [comment]
Kindly assign this issue to me, I'm eager to do that.

**Comment by ShamithaReddy** [comment]
should I add all the projects to the main page or should I only add the ones that are working?

**Comment by Astrodevil** [comment]
All Projects inside the repo are working, If you find some bug please raise the issue. Add all
