### ISSUE TITLE
Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by Atif0604** [ZeroOctave/ZeroOctave-Javascript-Projects#242]
**Describe the solution you'd like**
Add Tic-Tac-Toe Game

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [] Describe alternatives you've considered
- [] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
#189
