### ISSUE TITLE
Ball Game

### ISSUE THREAD

**Issue by Asttttha** [ZeroOctave/ZeroOctave-Javascript-Projects#245]
this a game that i have been working lately, there comes random holes, through which the ball is supposed to get passed, otherwise you lose.

i would like to make it look more professional, and later add some sound effects. also, to count and display the highscore made by user in the game itself.

i've attached a snapshot of it below, and this is my project link.

[(https://github.com/Asttttha/game)](https://asttttha.github.io/ball-game/)

- [✅] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [✅] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [✅] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

please assign me.

![image_2022-03-03_204725](https://user-images.githubusercontent.com/95849912/156593965-4d48a96c-e798-43ee-9903-a75d1986ec76.png)

**Comment by sreelakshmig009** [comment]
@Asttttha I have assigned you this issue. Work on the bug in your game before opening a pr

**Comment by Asttttha** [comment]
sure, thankyou

**Comment by Asttttha** [comment]
@sreelakshmig009  could you please tell me what bug? and how do i solve it

**Comment by sreelakshmig009** [comment]
> @sreelakshmig009 could you please tell me what bug? and how do i solve it

Score's value doesnt increase after 2 and becomes 1 again

**Comment by Asttttha** [comment]
> > @sreelakshmig009 could you please tell me what bug? and how do i solve it
> 
> Score's value doesnt increase after 2 and becomes 1 again

ok i'll fix it

**Comment by NOiR-07** [comment]
Any updates?? should i assign someone else or close this issue

**Comment by Asttttha** [comment]
@NOiR-07  no, actually i am having my sem. give me some time

**Comment by Asttttha** [comment]
@sreelakshmig009 @jeevanalok @NOiR-07 i've fixed it, check once.

**Comment by sreelakshmig009** [comment]
@Asttttha Have you pushed your commits to the repo?

**Comment by Asttttha** [comment]
> @Asttttha Have you pushed your commits to the repo? I'm still getting the error

yes, i've cross checked it too

**Comment by Asttttha** [comment]
@sreelakshmig009 do you mean the score does not add up with the prev score after the game is over? like it goes back to zero after every new start?

**Comment by jeevanalok** [comment]
@Asttttha i am a contributor just like you. No need to tag me
