### ISSUE TITLE
Please assign this issue to me, as I have worked on it

### ISSUE THREAD

**Issue by Parth-Shete** [ZeroOctave/ZeroOctave-Javascript-Projects#246]
This feature is related to the problem/issue that I am raising.

I will add the age feature in this issue using JavaScript as the main logic behind this task.
I will also add HTML and CSS to frame it in a nice order.

We can work on the CSS aspects of this issue.

I have worked with this feature before, so have the apt knowledge for it.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
It's not clear. What you want to solve and in which project.
