### ISSUE TITLE
No Try now Button for quiz app on the main html file

### ISSUE THREAD

**Issue by ShamithaReddy** [ZeroOctave/ZeroOctave-Javascript-Projects#249]
The try now button for How old is you? quiz is not visible.

I'm a GSSOC Contributor, please assign this issue to me.

![image](https://user-images.githubusercontent.com/73388412/156507517-adba661b-f7d1-4c17-b8a7-6610e8afdc27.png)

- ✅ I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- ✅ I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- ✅ I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Khushi25pandey** [comment]
I would like to work on this issue. Please assign it to me @ShamithaReddy
