### ISSUE TITLE
The Try now button for Auto write text is going out of the box

### ISSUE THREAD

**Issue by ShamithaReddy** [ZeroOctave/ZeroOctave-Javascript-Projects#250]
The Try now button for the Auto Write text card is going out of the box.

I'm a GSSOC contributor, kindly assign this issue to me.

![image](https://user-images.githubusercontent.com/73388412/156584995-e5115ac7-357d-4cc0-8761-42471913de3b.png)

- ✅ I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- ✅ I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- ✅ I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Astrodevil** [comment]
> I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

It's already assigned, feel free to raise new issue.
