### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by shrey2003** [ZeroOctave/ZeroOctave-Javascript-Projects#258]
I would like to add a tic tac toe game built using HTML,CSS,JS with some sound effects and interactive user interface. I am a GSSOC'22 participant.
.
### Code of Conduct✅
- [ ✅] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [✅ ] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [✅ ] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
[#189 ](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues/189)
