### ISSUE TITLE
Add footer to the website

### ISSUE THREAD

**Issue by khushigupta123** [ZeroOctave/ZeroOctave-Javascript-Projects#259]
### **Feature Description**

I would like to add a footer section in the website to give it a complete look.

### **About feature**

- Will Contain social media icons
- Notice for all rights reserved
- Compliment the style of website

I am a GSSOC 2022 participant,
Kindly assign this issue to me

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by sreelakshmig009** [comment]
@NOiR-07

**Comment by NOiR-07** [comment]
@khushigupta123 Will assign you soon

**Comment by NOiR-07** [comment]
> I want to work on this under GSSOC2022. Can you assign it to me.

Same issue cannot be assigned to 2 person at a time, try to raise other issue

**Comment by khushigupta123** [comment]
> @khushigupta123 Will assign you soon

okay 👍

**Comment by saketsagarsingh** [comment]
@khushigupta123 I want to work on this issue as I have prior experience regarding this issue please assign this issue to me

**Comment by NOiR-07** [comment]
@khushigupta123 assigned to you just whenever you start working make sure to keep updated your forked repo

**Comment by NOiR-07** [comment]
> @khushigupta123 I want to work on this issue as I have prior experience regarding this issue please assign this issue to me

she already raised the issue so let her to do, otherwise I'll assign it to you

**Comment by khushigupta123** [comment]
> @khushigupta123 assigned to you just whenever you start working make sure to keep updated your forked repo

Sure sir
