### ISSUE TITLE
Affine Cipher Calculator

### ISSUE THREAD

**Issue by AnIkeT126** [ZeroOctave/ZeroOctave-Javascript-Projects#279]
## Calculator Functions

The affine cipher is a type of monoalphabetic substitution cipher where each letter in an alphabet is mapped to its numeric equivalent, encrypted using a simple mathematical function, and converted back to a letter.

Text :  MONEY
a=11
b=4
Cipher: XGCRWI

**Describe the solution you'd like**

I would use HTML5, CSS3  & JS to take a user input and then decrypt and encrypt it based on the user's choice.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

Can I work on this issue as a part of GSSoC'22 @Astrodevil ?

**Comment by sreelakshmig009** [comment]
@AnIkeT126 We unfortunately already a cipher calculator project . Can you work on a new project or a bug or a feature and open a new issue?

**Comment by AnIkeT126** [comment]
@sreelakshmig009, so I checked the codes available and the issues created, and I found that the calculator available is for VIGNERE CIPHER, and I am proposing a one for AFFINE CIPHER, both being totally different in the method of approach.
Hence, if it's ok, can I move ahead or shall I drop it in either case.

**Comment by AnIkeT126** [comment]
can I get an update on this @NOiR-07 @sreelakshmig009 ?

**Comment by NOiR-07** [comment]
We already have 5-6 calculators in our project so try to add some different project or you can make a calculator and merge all these in one so the user can use any calculator he wants to
