### ISSUE TITLE
Add contributors images in readme 

### ISSUE THREAD

**Issue by pranjay-poddar** [ZeroOctave/ZeroOctave-Javascript-Projects#288]
**Is your feature request related to a problem? Please describe.**
Would like to add contributors and their images in the readme. Please Assign this task to me under GSSOC'22.

Features:

- user understandable UI
- Display the engagement of the repository and its activeness and popularity among the developers.
- Gives a sense of accomplishment to all the contributors.

### Steps Followed✅

- [X] Is your feature request related to a problem? Please describe.
- [X] Describe the solution you'd like
- [X] Describe alternatives you've considered
- [X] Additional context

### Code of Conduct✅
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [X] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
It's not needed. Contributors are already visible on right side of Repository.
