### ISSUE TITLE
Drums app using Java script

### ISSUE THREAD

**Issue by Mujeeb-shaikh7** [ZeroOctave/ZeroOctave-Javascript-Projects#290]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Are you proposing drum kit app like [This](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/Public/drum_kit.html)

**Comment by radzhiv25** [comment]
I am interested in resolving this issue

**Comment by Mujeeb-shaikh7** [comment]
This issue didn't got gssoc tag ,so i am gonna closing this issue

**Comment by Astrodevil** [comment]
> This issue didn't got gssoc tag ,so i am gonna closing this issue

Tags will be added by us, I asked you a question above. Answer that.
