### ISSUE TITLE
Try Now button is coming out of the Auto Write Text Card on Landing Page

### ISSUE THREAD

**Issue by shivam123-dev** [ZeroOctave/ZeroOctave-Javascript-Projects#291]
**Describe the bug**
Upon visiting the Landing Page the **Auto Write Text** card's **Try Now** button is coming out of the card 

**To Reproduce**
1. Go to [website](https://zerooctave.github.io/ZeroOctave-Javascript-Projects)
2. Scroll down to **Auto Write Text Card**

**Expected behavior**
The Try Now button should be present inside the card border like other cards

**Screenshots**
**Actual Behavior**
![image](https://user-images.githubusercontent.com/81038095/156896139-9306846c-2588-4d5b-a49c-928abe4a5f85.png)

**Expected Behavior**
![image](https://user-images.githubusercontent.com/81038095/156896172-de8bb0e3-d6d9-49fb-8a6f-86acd78e6c7a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 98.0.1108.62 (Official build) (64-bit)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by shivam123-dev** [comment]
> **Describe the bug** Upon visiting the Landing Page the **Auto Write Text** card's **Try Now** button is coming out of the card
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to [website](https://zerooctave.github.io/ZeroOctave-Javascript-Projects)
> 2. Scroll down to **Auto Write Text Card**
> 3. See error
> 
> **Expected behavior** The Try Now button should be present inside the card border like other cards
> 
> **Screenshots** **Actual Behavior** ![image](https://user-images.githubusercontent.com/81038095/156896139-9306846c-2588-4d5b-a49c-928abe4a5f85.png)
> 
> **Expected Behavior** ![image](https://user-images.githubusercontent.com/81038095/156896172-de8bb0e3-d6d9-49fb-8a6f-86acd78e6c7a.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Browser: Microsoft Edge
> * Version: 98.0.1108.62 (Official build) (64-bit)
> 
> ### Steps Followed✅
> Check the box with [x] If you followed all the steps.
> 
> * [x]  Describe the bug
> * [x]  To Reproduce
> * [x]  Expected behavior
> * [x]  Screenshots
> 
> ### Code of Conduct✅
> * [x]  I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
> * [x]  I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
> * [x]  I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

Kindly assign me this issue @Amitesh

**Comment by Astrodevil** [comment]
Solved in #250
