### ISSUE TITLE
Simple & Compound Interest Calculator 

### ISSUE THREAD

**Issue by Atharv-110** [ZeroOctave/ZeroOctave-Javascript-Projects#293]
**Is your feature request related to a problem? Please describe.**
When we go to bank or some banker who calculates simple or compound interest on anything it becomes difficult for him to calculate them as in normal calculator it is difficult to  remember what was the principle value how much rate was and etc.
**Describe the solution you'd like**
So here I want to make an Calculator which is only made up for calculating Simple and Compound Interest with separate field for principle value, rate, duration and etc.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### Consider this issue under GSSOC'22

**Comment by Atharv-110** [comment]
Label was not getting added

**Comment by Astrodevil** [comment]
Labels will be added by us.

**Comment by Atharv-110** [comment]
So sorry @Astrodevil sir that I've closed the issue and opened a new one can you please check #296 issue no. That is also opened by me consider that one. Please
