### ISSUE TITLE
Dice Game

### ISSUE THREAD

**Issue by dsasaank-369** [ZeroOctave/ZeroOctave-Javascript-Projects#301]
**Is your feature request related to a problem? Please describe.**
 I am a GSSOC22 contributor. I would like to add a Dice game built using HTML, CSS, JS.

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Ii already exists.
