### ISSUE TITLE
Adding Tic Tac Toe game

### ISSUE THREAD

**Issue by nithu2109** [ZeroOctave/ZeroOctave-Javascript-Projects#302]
**Is your feature request related to a problem? Please describe.**
I Would like to add Tic Tac Toe game in JavaScript. Please Assign this task to me under GSSOC'22.

### Features
- Score can be stored

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
#189
