### ISSUE TITLE
Adding Github Profiles Application

### ISSUE THREAD

**Issue by shivam123-dev** [ZeroOctave/ZeroOctave-Javascript-Projects#303]
**Is your feature request related to a problem? Please describe.**
I want to add a GitHub Profiles Application

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by shivam123-dev** [comment]
I am GSSOC'22 contributor. @Astrodevil Kindly assign me this issue

**Comment by Astrodevil** [comment]
Please explain, what type of GitHub profiles, provide more details

**Comment by shivam123-dev** [comment]
@Astrodevil 
 
It is an app which fetches an user's information from GitHub including his/her description, repo names, followers, followings and other details.

I am providing a screenshot of an example related the application which I want to add: -

## Screenshot
![example-image](https://user-images.githubusercontent.com/81038095/156966331-7349226d-eedd-4ffe-9083-7718e3b6c33e.png)

**Comment by shivam123-dev** [comment]
@Astrodevil Please review my PR #306
