### ISSUE TITLE
Live word counter giving wrong no. of alphabet

### ISSUE THREAD

**Issue by Ashish4321-hub** [ZeroOctave/ZeroOctave-Javascript-Projects#315]
Describe the bug
On giving integer as input alphabet count is increased
To Reproduce
Steps to reproduce the behaviour:
Make some in changes in count_alphabet function in word-count-calcultor

Expected behavior
Alphabet return wrong input and reload the page

Screenshots
![IMG_20220308_110119](https://user-images.githubusercontent.com/88235823/157175350-266ca412-ae67-4502-a0a8-f3253923c4ca.jpg)

**Smartphone (please complete the following information):
 - Device: realme narzo
 - Browser chrome
 
Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Describe the bug
- [ ] To Reproduce
- [ ] Expected behavior
- [ ] Screenshots
- [ ] Additional context

 Code of Conduct✅
- [ ] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ ] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ ] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by AnIkeT126** [comment]
can I work on this issue under GSSoC'22?

**Comment by Astrodevil** [comment]
@Ashish4321-hub Will you work on it? or I can assign someone else?

**Comment by AnIkeT126** [comment]
@Astrodevil if you are reassigning, please consider me.

**Comment by sreelakshmig009** [comment]
> @Astrodevil if you are reassigning, please consider me.

I have assigned this issue to the issue creator. Please feel free to raise a new one

**Comment by Rishita489** [comment]
hey @Astrodevil , I am a GSSOC'22 contributor . Can you please assign this issue to me . I have send the PR solving the above issue . Can you please review and merge it .

**Comment by Rishita489** [comment]
hey @Astrodevil , I have solved this issue and PR is also merged . but it has not been counted in my GSSOC PRs .

**Comment by Astrodevil** [comment]
@Rishita489 I will check the labels, don't worry. Will let you know in few hours.
