### ISSUE TITLE
Developer portfolio website 

### ISSUE THREAD

**Issue by MannyP31** [ZeroOctave/ZeroOctave-Javascript-Projects#330]
This developer portfolio website is made using HTML , CSS and javascript . It is entirely responsive as well as has minimal UI.<br><br>
Landing Page :<br>
![Screenshot (628)](https://user-images.githubusercontent.com/76945004/157404258-fabfb2a2-d3fd-415a-a905-728f82c33fcf.png)<br><br>
![Screenshot (629)](https://user-images.githubusercontent.com/76945004/157404266-320295a8-1d55-40d4-b73d-b37579a4224f.png)

@JayantGoel001 kindly assign me the issue to start working on the project.

**Comment by JayantGoel001** [comment]
@Astrodevil @NOiR-07 @sreelakshmig009 Please Assign this to @MannyP31
