### ISSUE TITLE
Readme Updation

### ISSUE THREAD

**Issue by ayush-sleeping** [ZeroOctave/ZeroOctave-Javascript-Projects#331]
**Is your feature request related to a problem? Please describe.**
The Readme section is not that much responsive .

**Describe the solution you'd like**
Want to make it more responsive and up to date .

**Additional context**
The features , I want to add are 
1. Add more labels (contributors no., License, Issue closed, Pull req. open, Closed Pull req. ) ,
2. Add Report Bug link,
3. Add Request Project link,
4. Add Table of content ,
5. Add ( back to top - button ) and ( bottom - button ) links ,
6. Make a table for Projects which are available in this repo. ,
7. Add Contributors section ,
8. Add Feedback ,
9. All things categorize it, In a systematic way ......

#

By adding all these features the Readme of this awesome repo. become more responsive and more amazing .

# 

HEY Project Maintainers,
I want to work on this issue under GSSOC'22,

# 

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Don't add unnecessary labels. 7th point is not needed. Table of contents should be under toggle.

**Comment by ayush-sleeping** [comment]
ok @Astrodevil , 
I will not add 7th point
