### ISSUE TITLE
new design to calculator

### ISSUE THREAD

**Issue by LegendSumeet** [ZeroOctave/ZeroOctave-Javascript-Projects#337]
**Is your feature request related to a problem? Please describe.**
no, its looks will get better

**Describe the solution you'd like**
 features like basic mode advanced mode and scientific mode calculation

**Describe alternatives you've considered**
design and look of it

**Additional context**
basic mode advanced mode and scientific mode

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by LegendSumeet** [comment]
@NOiR-07 assign me

**Comment by NOiR-07** [comment]
> @NOiR-07 assign me

sure
