### ISSUE TITLE
Beautifying the home page

### ISSUE THREAD

**Issue by kritsss** [ZeroOctave/ZeroOctave-Javascript-Projects#343]
**Is your feature request related to a problem? Please describe.**
The home page looks kind of shabby and the color theme isn't appropriate, I want to fix the front-end so that it attracts more users.

**Describe the solution you'd like**
I want to add text animations, logo animations and suitable pictures/videos/gifs.

**Describe alternatives you've considered**
I will change the font-family of the page, decide appropriate color theme, add animations accordingly. Also, a brief description of what the website is about will look good.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Mayankrawat374** [comment]
**Is your feature related to a problem? please describe**
Front-end of any website is the first most important thing so, it must look good and attractive so, that more and more user's revisit and stay long as I found that your website lack in that so I want to work on the front-end  of this website.

**Describe the solution you'd like**
I want to add some different colors, add some font-family, add some new pictures to it.

**Describe alternatives you've considered**
I will add a feature in which if you hover to any blog the background color will change accordingly, add font-family which make the website look more professional and interactive.

I'll definitely make your website more dynamic and user friendly .

**Comment by Astrodevil** [comment]
@kritsss Don't make html file too complex, It's easy to add new project as of now.
