### ISSUE TITLE
Rock Paper Scissors Game

### ISSUE THREAD

**Issue by prer45** [ZeroOctave/ZeroOctave-Javascript-Projects#346]
I would like to add the popular Rock Paper Scissors game built using HTML,CSS,JS. I am a GSSOC22 participant.
### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
@prer45 Sorry but I have to close this issue because this already exists. Feel free to raise a new one or contact one of us mentor for doubt or support
