### ISSUE TITLE
Add projects in README

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#359]
Add every projects from our repo in **Available Projects** section in README. Don't break consistency, Don't repeat.

**Comment by mahiiverse1** [comment]
Hi just to ask, I have updated the projects, so will there be more projects added later and then do i keep updating this again? or do i make a PR for the changes made till now? (for all the projects that are available as of now)

**Comment by Astrodevil** [comment]
You can update new projects on frequency of 1 week if you want.

**Comment by mahiiverse1** [comment]
Okay got it!
