### ISSUE TITLE
Add attractive LOGIN page 

### ISSUE THREAD

**Issue by theplayer9** [ZeroOctave/ZeroOctave-Javascript-Projects#362]
**Is your feature request related to a problem? Please describe.**
When to start the web page it directly jumps to the landing page. It's good but it lacks the sense of authentication.

**Describe the solution you'd like**
To tackle this issue I think we can create an attractive Login page for better user experience .
We can do so with the help of glassmorphism using Tailwnd css ,Tilt js ,React js.

**Describe alternatives you've considered**
If not with glassmorphism and tilt js then , we can do so with just simple JavaScript

**Additional context**
![Screenshot (96)](https://user-images.githubusercontent.com/79765871/158124079-9bec50ec-eb36-4e4b-afdc-2e297c7897e4.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x ] Is your feature request related to a problem? Please describe.
- [ x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [ x] Additional context

### Code of Conduct✅
- [x ] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
@Astrodevil

**Comment by Astrodevil** [comment]
Multiple login page are already in this repo or assigned to someone, Work on something else @theplayer9
