### ISSUE TITLE
Write or Add Your Articles

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#375]
If you are a **tech writer** and writing about **Open Source, Opportunities, Resources** related to tech and learning.

You are Invited to contribute your articles in [ZeroOctave Blog](https://zerooctave.hashnode.dev/) on Hashnode.
- Join Hashnode [Here](https://hashnode.com/@Astrodevil/joinme)
- Join Blog Team [Here](https://hashnode.com/teams/invite/0013e746-aa30-4335-9196-5dd3bed50715)

**Note:** This contribution will not be counted under GSSoC22.

**Comment by mahiiverse1** [comment]
Is there a certain topic thats being expected from us to write about or just any tech blogs in general? Also since this is not counted towards gssoc im assuming theres no due date and i dont have to make a PR? Im willing to contribute but im confused

**Comment by Astrodevil** [comment]
@mahiiverse1 no need to raise PR. Just visit given links and start writing. Contents/Topics related to Open Source, Opportunities, Learning Experiences and Tech Resources.

**Comment by Astrodevil** [comment]
No, program Is ended now. Only code contributions counted.
