### ISSUE TITLE
Third Degree Equation Calculator

### ISSUE THREAD

**Issue by XZANATOL** [ZeroOctave/ZeroOctave-Javascript-Projects#376]
**Is your feature request related to a problem? Please describe.**
I would like to add a responsive calculator that solves equations of third degree (ax^3 + bx^2 + cx + d = 0) and prints out the 3 roots.

**Describe the solution you'd like**
The calculator will be able to deal with complex/imaginary solutions and it will make use of: HTML / CSS / Bootstrap5 / JS

**Additional context**
Issue made under GSSoC'22 contributions 

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Manik-Aggarwal** [comment]
Please assign it to me, i m a gssoc 2022 contributor

**Comment by sreelakshmig009** [comment]
@XZANATOL Your calculator will solve only polynomial equations right

**Comment by XZANATOL** [comment]
@sreelakshmig009 Not only polynomials, It should be able to solve other roots and imaginary solutions as mentioned in the issue body.
