### ISSUE TITLE
home page 

### ISSUE THREAD

**Issue by leesha19** [ZeroOctave/ZeroOctave-Javascript-Projects#382]
**Is your feature request related to a problem? Please describe.**

_home page of the website is not so attractive_ 

**Describe the solution you'd like**
i would like to improve the home page of the website using html an css so it can be more interactive for the user 
**Describe alternatives you've considered**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
@Astrodevil

**Comment by Astrodevil** [comment]
@leesha19 Can you please explain what things you want to add or change on home page.

**Comment by leesha19** [comment]
> @leesha19 Can you please explain what things you want to add or change on home page.
i would like to change the theme of the website its very improper
