### ISSUE TITLE
Add a drawing website

### ISSUE THREAD

**Issue by kheya19** [ZeroOctave/ZeroOctave-Javascript-Projects#386]
I can add a drawing website in which you can draw, change the color of the pen, and also the thickness of the stroke.
I can make it using HTML, CSS, and  js

**Comment by Srushti-Naik** [comment]
I'm GSSOC'22 contributor please assign this task to me.

**Comment by sreelakshmig009** [comment]
Sounds very interesting. Good luck working on this issue

**Comment by kheya19** [comment]
> Sounds very interesting. Good luck working on this issue

![screenshot-127.0.0.1_5500-2022.03.30-18_12_07.png](https://user-images.githubusercontent.com/91829546/161922653-e9d6afc4-650d-45c6-92f4-675a8532e350.png)
I have made this but I am not able to make a pull request because I have already made a pull request for Microsoft clone and that is still pending .
