### ISSUE TITLE
Tik-Tac-Toe Game

### ISSUE THREAD

**Issue by RavishaNewase** [ZeroOctave/ZeroOctave-Javascript-Projects#387]
I will be creating tic-tac-toe game using js.
Please assign me this under GSSoC'22

**Comment by SonikeshKumar14** [comment]
plz assign to me i am creating tic-tac-toe game by using javasript

**Comment by TG922** [comment]
Guys, Please check https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues/189

It is already created !!

**Comment by sreelakshmig009** [comment]
Closing this issue as it's a duplicate. @RavishaNewase @SonikeshKumar14 Feel free to create new issues or work on bugs. In case you guys have any doubt, contact us through our discord channel
