### ISSUE TITLE
Add scroll to top button to main website

### ISSUE THREAD

**Issue by Siddhesh777** [ZeroOctave/ZeroOctave-Javascript-Projects#391]
**Is your feature request related to a problem? Please describe.**
Sometimes User want to go to the top of the page after scrolling a lot.

**Describe the solution you'd like**
I want to make a button which will take a user to the top of the page.

**Additional context**
I am contributor at gssoc'22.
Please assign this task to me.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by pushpanjali-10** [comment]
I'm Contributor in GSSoC22 . Can u assign this to me.

**Comment by sreelakshmig009** [comment]
@NOiR-07 @Astrodevil
