### ISSUE TITLE
Search Button

### ISSUE THREAD

**Issue by Siddhesh777** [ZeroOctave/ZeroOctave-Javascript-Projects#393]
**Is your feature request related to a problem? Please describe.**
If a user wants to go to a particular project then it is very tedious work to scroll down and find the project.

**Describe the solution you'd like**
I think we can make a search bar at the top so that the user can search for a project and check it out very easily and fast.

**Additional context**
I am contributor at gssoc'22.
Please assign this task to me.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

![1](https://user-images.githubusercontent.com/77476772/159167990-237445a9-cd29-467e-95ff-6ce6c1ae09d1.png)
We will take care of UI later on.

**Comment by pushpanjali-10** [comment]
I'm Contributor in GSSoC22 . Can u assign this to me.

**Comment by sreelakshmig009** [comment]
@Siddhesh777 Sorry about this but I have assigned the same issue to someone else. Feel free to work on any other issue
