### ISSUE TITLE
Function Grapher

### ISSUE THREAD

**Issue by XZANATOL** [ZeroOctave/ZeroOctave-Javascript-Projects#394]
**Is your feature request related to a problem? Please describe.**
I would like to add a JS app that graphs a provided function of x.

**Describe the solution you'd like**
The script should graph function of x like:
* x^2
* x^3 + x + 25
* sin(x)

**Additional context**
Issue made under GSSoC'22 contributions.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
Love these unique ideas. Good luck
