### ISSUE TITLE
Log and antilog calculator

### ISSUE THREAD

**Issue by Siddhesh777** [ZeroOctave/ZeroOctave-Javascript-Projects#401]
**Is your feature request related to a problem? Please describe.**
So many times it is difficult to calculate log and antilog to some base
.
**Describe the solution you'd like**
I would like to make a logarithmic and anti logarithmic calculator.

**Additional context**
I am contributor at gssoc'22.
Please assign this task to me.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by NOiR-07** [comment]
already many calculators exists in project
