### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by pranavsuriya-sr** [ZeroOctave/ZeroOctave-Javascript-Projects#426]
**Describe the bug**
The back to top button isn't working.

**To Reproduce**
1. Go to the website.
2. Scroll down a bit.
3. Click on the back to top button.
4. After clicking it wont navigate.

**Expected behavior**
After clicking the button we should be directed to the top.

**Desktop (please complete the following information):**
  - Browser - chrome

- [X] Describe the bug
- [X] To Reproduce
- [X] Expected behavior

### Code of Conduct✅
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [X] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by naugsss** [comment]
It's 6th of April Today and as of now that scroll button is still not working, please assign this issue to me so that I can make the necessary changes in the project

**Comment by pranavsuriya-sr** [comment]
> It's 6th of April Today and as of now that scroll button is still not working, please assign this issue to me so that I can make the necessary changes in the project

Please wait as the pull request is still not merged. The pr was made 4 days ago. Refer to pr number #437 for more info.
