### ISSUE TITLE
I want to add a TIC TAC TOE game based on C++

### ISSUE THREAD

**Issue by Amulya77** [ZeroOctave/ZeroOctave-Javascript-Projects#43]
MY game is based on minimax algorithm 
Belo is a  image showing How the algo works.
![minimax_vis](https://user-images.githubusercontent.com/79034752/135522604-788e46fb-c71b-49f5-8cad-7741cd5d843f.png)

**Comment by AbhayTrivedi** [comment]
I would like to work on that

**Comment by NOiR-07** [comment]
> I would like to work on that

Sorry, It has been assigned to @Amulya77 as he raised the issue first.
You can visit the repo and see other projects to contribute in

**Comment by Astrodevil** [comment]
@Amulya77 This repo contains only web dev projects! why you are adding C++ project

Assigned by mistake
