### ISSUE TITLE
Word count calculator Enhancement

### ISSUE THREAD

**Issue by devanshtivari** [ZeroOctave/ZeroOctave-Javascript-Projects#44]
I have gone through word-count-calculator.html and found it very basic. I can add more features to it and make it more descriptive.

**Comment by devanshtivari** [comment]
![image](https://user-images.githubusercontent.com/85034975/135525066-0dcc00ef-6a3f-4799-90e5-0e9e07d6e050.png)

This is the page and I want to enhance its appearance and functionality.

**Comment by NOiR-07** [comment]
Yes sure, go ahead
