### ISSUE TITLE
landing page footer

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#447]
Footer section of [landing page](https://zerooctave.github.io/ZeroOctave-Javascript-Projects/) is quite messy after recent commit. Make it good.

**Comment by gurjeetsinghvirdee** [comment]
assign me

**Comment by debadrita612** [comment]
@Astrodevil please look into PR #445 . I have added my project stopwatch application (issue #428). Along with that I also tried to sort out the bug in the footer section. Hopefully it will be sorted out. The mess was created due to my previous PR #410 which was merged earlier.
