### ISSUE TITLE
Footer part is repeated twice.

### ISSUE THREAD

**Issue by Ranjana550** [ZeroOctave/ZeroOctave-Javascript-Projects#454]
Heyy @NOiR-07, The footer part of a website is repeated twice and one project is also not aligned perfectly.
![image](https://user-images.githubusercontent.com/71266173/161896222-8ba21292-9a58-4542-b54a-3c4431849429.png)

I am a GSSoC contributor and would like to work on this issue. Kindly assign it to me.

**Comment by connectnitesh** [comment]
Hello @sreelakshmig009 and @NOiR-07 I want to work on this issue!

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue. Please assign me as a GSSOC 2022 Contributor.
