### ISSUE TITLE
Add a Udemy Clone

### ISSUE THREAD

**Issue by naugsss** [ZeroOctave/ZeroOctave-Javascript-Projects#456]
I want to add a udemy login page clone in your project under Gssoc'22.
Please assign me this project!

Something like this : 

![udemy](https://user-images.githubusercontent.com/89718207/161986962-e4c130ea-370d-4848-964e-9bbf25db79b3.jpg)

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue? Then assign me this @sreelakshmig009
