### ISSUE TITLE
Front end of a blog website. can i contribute here?

### ISSUE THREAD

**Issue by TadrupDas** [ZeroOctave/ZeroOctave-Javascript-Projects#468]
I have already completed the front end part of a blog website. Can i contribute here?

**Comment by sreelakshmig009** [comment]
> I have already completed the front end part of a blog website. Can i contribute here?

Yesss sure, go ahead. Atb.

**Comment by TadrupDas** [comment]
Ok. At first i have to clone ,edit and then pull request right? @sreelakshmig009

**Comment by sreelakshmig009** [comment]
> Ok. At first i have to clone ,edit and then pull request right? @sreelakshmig009

yes abd mention this issue in your pr
