### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by khushigupta123** [ZeroOctave/ZeroOctave-Javascript-Projects#485]
**Is your feature request related to a problem? Please describe.**

I noticed that the website does not have a favicon as of now.

### **Importance of favicon**

- Make website attractive
- Provide individuality to the website
- Make it easier for users to find website tab among other tabs

**Describe the solution you'd like**
I will design a creative and artistic favicon for this website.

**Describe alternatives you've considered**
Logo of Zero Octave can also be used as the website favicon but a newly designed favicon will help the users to understand what this particular website is about at a glance.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by connectnitesh** [comment]
Hey @NOiR-07 I would like to work on this issue!

**Comment by sreelakshmig009** [comment]
> Hey @NOiR-07 I would like to work on this issue!

@connectnitesh Since she raised the issue first, I have assigned it to her. Feel free to work on other issues
