### ISSUE TITLE
Basic physics calculator

### ISSUE THREAD

**Issue by RiyaJain12** [ZeroOctave/ZeroOctave-Javascript-Projects#490]
**Is your feature request related to a problem? Please describe.**
I am a GSSoC'22 contributor.I would like to add basics basic calculator to this website and wanted to contribute in this project!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by RiyaJain12** [comment]
please assign me!

**Comment by Astrodevil** [comment]
Many calculators are already here in this repository, try to contribute some other project.
