### ISSUE TITLE
RGB Game

### ISSUE THREAD

**Issue by Whizz76** [ZeroOctave/ZeroOctave-Javascript-Projects#492]
Hi, I am a GSSOC'22 contributor, and I want to add a rgb game where the user gets a set of 3-6 blocks of different colors and he/she needs to select the block having color same as that shown on the screen.

**Comment by Astrodevil** [comment]
can you provide screenshot of what you are suggesting. More details will be helpful because similar project exists.

**Comment by Whizz76** [comment]
Yes, 
![20220419_112833](https://user-images.githubusercontent.com/89126404/163936027-b2096115-88fc-4bec-9f06-9ed72f2eddfc.jpg)
![20220419_112849](https://user-images.githubusercontent.com/89126404/163936055-b921d5c1-103a-40ee-97d2-568c8c2d9990.jpg)
