### ISSUE TITLE
image is broken down

### ISSUE THREAD

**Issue by Sunil4510** [ZeroOctave/ZeroOctave-Javascript-Projects#507]
**Describe the bug**
   image is broken down.

**To Reproduce**
1. Go to https://zerooctave.github.io/ZeroOctave-Javascript-Projects/
3. Scroll down to "BMI calculator"

**Expected behavior**
image should be displayed.
**Screenshots**
![Screenshot (114)](https://user-images.githubusercontent.com/77005171/163702205-e05dab48-82a7-4948-b36a-61a21e10035f.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
After fixing this, Also make multiple pages because a huge number of projects don't look good on a single page.
