### ISSUE TITLE
Arrange cards in a uniform manner

### ISSUE THREAD

**Issue by Adhetya** [ZeroOctave/ZeroOctave-Javascript-Projects#508]
**Describe the bug**
Cards are not arranged properly

**To Reproduce**
1. Go to the website
3. Scroll down to see alignment of cards

**Expected behavior**
Cards should be arranged in a uniform manner and also be of equal size

**Screenshots**
<img width="1440" alt="Screenshot 2022-04-17 at 9 31 22 PM" src="https://user-images.githubusercontent.com/20537150/163722626-f3df959f-00b1-406b-bf68-600d6bd81f0f.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I am a GSSOC 22 contributor.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Assigned in #507
