### ISSUE TITLE
Polynomial Long Division Calculator

### ISSUE THREAD

**Issue by Salma-Hamed** [ZeroOctave/ZeroOctave-Javascript-Projects#510]
**Is your feature request related to a problem? Please describe.**
This application performs the long division of polynomials.

**Describe the solution you'd like**
1. To divide a polynomial by another one:
        - Enter each polynomial in terms of x or X, without spaces between each term.
        - Use the power symbol (^) for terms with order more than one.
        - Click on (Divide) button.
2. To perform another division operation click on (Clear) button.

I am a GSSoC'22 participant. Please assign it to me.

**Describe alternatives you've considered**
--

**Additional context**
I have uploaded it on GitHub which URL is given below:
(https://github.com/Salma-Hamed/Polynomial-Long-Division-Calculator).

![calc](https://user-images.githubusercontent.com/71777717/163855067-37a91d7d-435b-4fb7-885a-ed5960fd7b97.PNG)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
So many types of calculators already exists in this repository, So we will not accept more. You are welcome to contribute other projects.
