### ISSUE TITLE
Improve overall UI of the website. 

### ISSUE THREAD

**Issue by Abh1shekSingh** [ZeroOctave/ZeroOctave-Javascript-Projects#512]
**Describe the bug**
I can improve everything 
1. the navbar
2. the cards
3. the color
4. alignments and many more
5. Responsive ness

- [x] Describe the bug

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Abh1shekSingh** [comment]
Please assign th taks to me

**Comment by Astrodevil** [comment]
Also break it into multiple pages, because large no. of project on same page is not attractive.

**Comment by Abh1shekSingh** [comment]
I will

**Comment by Astrodevil** [comment]
use official image/logo of this org if needed.

**Comment by Abh1shekSingh** [comment]
@Astrodevil  Hey Listen, Everything is done, beside Backend. and backend has alot of work to do. I will make another issue, and then make new separate PR for it. Cause backend will take extra time. and I think I deserve more points for that. Well this is what frontend looks like right now
 Changes i proposed till now. 

1. I separate out backend from .html file
2. made a navbar which is responsive
3. make more attractive cards
4. footer was twice, made changes there.
5. search bar design changes
6. overall touch up

![sample](https://user-images.githubusercontent.com/71981463/163979005-c8cc39f4-14ff-4fe3-995b-3926a7324650.JPG)

**Comment by Abh1shekSingh** [comment]
@Astrodevil tell me your decision. Then I will make PR for frontend now and create another issue for backend and make PR for backend then

**Comment by Astrodevil** [comment]
You must do every addition of image and naming of projects properly on landing page. If you have to make larger changes by adding Backend then only make new PR.

**Comment by Abh1shekSingh** [comment]
See, abb pata kya krna baaki hai, sirf projects ke NAM, LINKS and  IMAGES json file mein likhna baaki hai, aur uske liye more time and mehnat chaiye, so thats why I said

**Comment by Abh1shekSingh** [comment]
Baaki design kaisa laga, bta do kuch change krna hai toh

**Comment by Astrodevil** [comment]
Colour theme: It would be better if taken from org logo. 

& use images of each project on cards.

**Comment by Abh1shekSingh** [comment]
1. images toh jab backend pe work kruga tab change ho jayegi
2. I will see what i can do for multiple pages
3. color theme change krta hu, (current color theme mene Javascript waali rkhi thi actually, javascript ka logo yellow hota hai so thats why)

**Comment by Abh1shekSingh** [comment]
Please mujhe multiple pages ka concept thoda aur elaborate karo

**Comment by Abh1shekSingh** [comment]
Database mein saari cheeze add krne mein toh bhut wqt lg jana hai, koi aur bhi help krde toh badhiya hai,

**Comment by Astrodevil** [comment]
> Please mujhe multiple pages ka concept thoda aur elaborate karo( Like ek page pe 20-30 Projects) ?

20 projects per page kr skte to krdo. If not leave as it is, will change later. Use org logo/picture as website fevicon.

**Comment by Abh1shekSingh** [comment]
App yeh waali merge krlo, so that jb new branch create kru toh yeh changes reflect ho jaaye
