### ISSUE TITLE
Random Password Generator 

### ISSUE THREAD

**Issue by Aayush987** [ZeroOctave/ZeroOctave-Javascript-Projects#541]
**Feature Description**
A random password generator that generates up to 4 random passwords of length at one time. This issue is under GSSOC'22 contributions.

**Additional context**
![passwd](https://user-images.githubusercontent.com/92387745/164734020-4bc5c3e2-0c11-460e-8f11-1666991116bd.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Already exists.
