### ISSUE TITLE
Add a Drink Water Application in HTML CSS & JS 

### ISSUE THREAD

**Issue by pranjay-poddar** [ZeroOctave/ZeroOctave-Javascript-Projects#550]
**Is your feature request related to a problem? Please describe.**
Would like to add a Drink Water Application in HTML CSS & JS. Please Assign this task to me under GSSOC'22.

Features:
- It will alert a user according to the water intake and the adequate water requirements.
- user understandable UI
- sound effects 
- animations
- score storage

### Steps Followed✅

- [X] Is your feature request related to a problem? Please describe.
- [X] Describe the solution you'd like
- [X] Describe alternatives you've considered
- [X] Additional context

### Code of Conduct✅
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [X] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
#434

**Comment by pranjay-poddar** [comment]
@Astrodevil may I know why this issue is closed coz as I can see #434 was not added/merged and it's already been closed.

**Comment by Astrodevil** [comment]
It's not yet closed.

**Comment by sreelakshmig009** [comment]
@pranjay-poddar Sorry for the late assignment go ahead with your project

**Comment by pranjay-poddar** [comment]
@sreelakshmig009 @Astrodevil please review my application
