### ISSUE TITLE
Want to add a project of a  music website(Musify)

### ISSUE THREAD

**Issue by DeveloperAshish8** [ZeroOctave/ZeroOctave-Javascript-Projects#564]
It is a music website with HTML, CSS and JAVASCRIPT
![Screenshot (31)](https://user-images.githubusercontent.com/90233808/165033730-70bb8672-82c5-4235-bfcc-fb59d8224bd3.png)
.

**Comment by DeveloperAshish8** [comment]
I am a GSSoC participant please assign me this issue

**Comment by Astrodevil** [comment]
@DeveloperAshish8 Is this a music player? If yes, it's already in the repo with different UI.

**Comment by DeveloperAshish8** [comment]
@Astrodevil but both are completely different. Should I add the new Musify?

**Comment by Astrodevil** [comment]
Go ahead
