### ISSUE TITLE
Add a rock paper scissors game

### ISSUE THREAD

**Issue by Shelly011s** [ZeroOctave/ZeroOctave-Javascript-Projects#565]
Feature Description
A rock paper scissors game that you can play with the computer. This issue is under GSSoC'22 Contributions.

Steps Followedwhite_check_mark

Check the box with [x] If you followed all the steps.

-[ ] Is your feature request related to a problem? Please describe.
-[x] Describe the solution you'd like
-[ ] Describe alternatives you've considered
-[ ]Additional context

Code of Conductwhite_check_mark

-[x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
-[x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
-[x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Shelly011s** [comment]
Please assign this issue to me.

**Comment by Astrodevil** [comment]
Already exists
