### ISSUE TITLE
Some Projects are not working properly

### ISSUE THREAD

**Issue by Aayush987** [ZeroOctave/ZeroOctave-Javascript-Projects#567]
**Describe the bug**
Some projects on the site are not working properly due to not proper path mention to its CSS and JS files or some error in HTML code. There are at least 4-to 5 projects which are not working properly. This is under GSSOC'22 contributions.

**To Reproduce**

**Expected behavior**
It should be working properly by resolving small yet faulty errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/92387745/165225001-42efc4d0-58d0-4b94-bd6f-342df180cc16.png)
![image](https://user-images.githubusercontent.com/92387745/165225019-714e5c83-f543-452b-9c97-fe06251fbd94.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [ ] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
Hey thanks for raising this issue. Ill assign you this issue but please specify the bugs that you'll be working with, like email validator project

**Comment by Aayush987** [comment]
> Hey thanks for raising this issue. Ill assign you this issue but please specify the bugs that you'll be working with, like email validator project

OK, I will specify the project name in the pr.
