### ISSUE TITLE
conversion calculator 

### ISSUE THREAD

**Issue by kevinmody** [ZeroOctave/ZeroOctave-Javascript-Projects#577]
My idea is to create a code that will convert from cm to meters, meters to feet, etc. 

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Looked for duplicates
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
Closing this issue because we have a similar project. Feel free to brainstorm on a new one
