### ISSUE TITLE
Advanced BMI Calculator

### ISSUE THREAD

**Issue by kevinmody** [ZeroOctave/ZeroOctave-Javascript-Projects#578]
I saw a BMI calculator on one of the repositories, but it only does metric, but mine does metric and imperial. So, I will like this added to this repository.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [X] Describe the solution you'd like
- [X] Describe alternatives you've considered
- [X] Additional context

### Code of Conduct✅
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [X] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for the same problems.
- [X] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
Closing this issue because we have the same project already. Feel free to work on a new issue
