### ISSUE TITLE
Blurry Loading

### ISSUE THREAD

**Issue by nouraan-ahmed** [ZeroOctave/ZeroOctave-Javascript-Projects#589]
### Demo
![blurry_loading](https://user-images.githubusercontent.com/52378608/165943275-15c894c8-2bff-4f9f-a0d4-b52421b31d9d.gif)

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sreelakshmig009** [comment]
@Astrodevil

**Comment by Astrodevil** [comment]
> @Astrodevil

?
