### ISSUE TITLE
Image Filter App

### ISSUE THREAD

**Issue by Atif0604** [ZeroOctave/ZeroOctave-Javascript-Projects#602]
**Describe the solution you'd like**
A webapp that help you to edit your photos and apply custom filter

**Additional context**
<img width="960" alt="Image-Filter-App" src="https://user-images.githubusercontent.com/64218887/166492565-a71ab8a5-4482-42eb-b8c7-afd54c661e91.png">

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Atif0604** [comment]
Please Assign me under GSSOC'22

**Comment by Astrodevil** [comment]
Image editor already exists, please check if you can enhance that.

**Comment by Atif0604** [comment]
> Image editor already exists, please check if you can enhance that.

yeah i have pre applied filter and custom settings

**Comment by Atif0604** [comment]
> Image editor already exists, please check if you can enhance that.

yeah sure

**Comment by Atif0604** [comment]
Hey @Astrodevil could you pls assign me
