### ISSUE TITLE
Login Form

### ISSUE THREAD

**Issue by sshiwangi** [ZeroOctave/ZeroOctave-Javascript-Projects#612]
**Is your feature request related to a problem? Please describe.**
In the login form project, nothing is happening on clicking Forget your password text.

**Describe the solution you'd like**
I would like to add a new form option through which user can reset their password. It will ask for their email Id and will also have a button to send further instructions. 
Also i would like to add a background image that complements the form well.

**Describe alternatives you've considered**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).
![reset password](https://user-images.githubusercontent.com/77545230/167247071-209d281e-9b55-4cfa-a304-3aa37b3ed19c.png)

**Comment by parthaggarwal30** [comment]
@sshiwangi I'm Gssoc 2022 contributor and i came across this eroor in one of my projects and it has been fixed completely. So i would like this to get assigned to me please
