### ISSUE TITLE
Add a dynamic picture frame 

### ISSUE THREAD

**Issue by Whizz76** [ZeroOctave/ZeroOctave-Javascript-Projects#618]
Add a dynamic picture frame that allows us to 
manipulate CSS with JavaScript by Coding a Dynamic Picture Frame

**Comment by Astrodevil** [comment]
can you share any screenshot or running project example?

**Comment by Whizz76** [comment]
Yes here is the screenshot of the project.
![20220510_091635](https://user-images.githubusercontent.com/89126404/167538351-e7f6e83e-973a-46db-88c4-1f7f401d4e74.jpg)

**Comment by Whizz76** [comment]
please assign it to me
