### ISSUE TITLE
Song and weather website with API

### ISSUE THREAD

**Issue by aaryahjolia** [ZeroOctave/ZeroOctave-Javascript-Projects#627]
A Website where one can listen songs according to genre choosen and also to know the weather of any place. All this with the help of an API.

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by aaryahjolia** [comment]
@Astrodevil Please assign

**Comment by sreelakshmig009** [comment]
Hi, unfortunately, we have similar projects on the website.  I strongly encourage you to work on new issues/bugs.
