### ISSUE TITLE
Music Player not working

### ISSUE THREAD

**Issue by SachinMittal1766** [ZeroOctave/ZeroOctave-Javascript-Projects#639]
**Describe the bug**
Music player is not working.

**Expected behavior**
It should work & play songs.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [ ] To Reproduce
- [x] Expected behavior
- [ ] Screenshots
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Provide screenshot

**Comment by SachinMittal1766** [comment]
![Screenshot (1047)](https://user-images.githubusercontent.com/82721772/168284503-140df4b3-e16c-4ab4-afce-45df5ec02156.png)
It is giving errors when I press any button.
