### ISSUE TITLE
Want to contribute full stack/react/backend based Projects ❓

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/ZeroOctave-Javascript-Projects#651]
**We are not accepting react project in this repository. But, You can contribute full stack/react/backend based project in our other repository**. 

[Full-Stack-Web-Development-Projects](https://github.com/ZeroOctave/Full-Stack-Web-Development-Projects)

Raise Issue or create pull request.

**Comment by manmohan4142** [comment]
Please accept my pr i have created a javascript project.. @Astrodevil
