### ISSUE TITLE
Add a customized task list app

### ISSUE THREAD

**Issue by Whizz76** [ZeroOctave/ZeroOctave-Javascript-Projects#655]
Hi, I am a GSSOC'22 contributor and I want to add a customized task adding app that allows users to add their everyday tasks, these tasks are retained in the app even if the user refresh the browser.

**Comment by komalsoni4** [comment]
please assign this issue to me

**Comment by sreelakshmig009** [comment]
Unfortunately we already have similar projects. Hence I request you to work on a new issue
