### ISSUE TITLE
Blur DOM loader 

### ISSUE THREAD

**Issue by RAHULBAWA777** [ZeroOctave/ZeroOctave-Javascript-Projects#658]
Dom Loads With a blur effect /assign

**Comment by Astrodevil** [comment]
can i see your screenshot? Similar project may already exists.

**Comment by RAHULBAWA777** [comment]
> can i see your screenshot? Similar project may already exists.

https://user-images.githubusercontent.com/91609324/168517923-f52fc509-f2ce-48ff-ab3f-6cd74d45d5a9.mp4

here you go bro :)

**Comment by RAHULBAWA777** [comment]
@Astrodevil ..

**Comment by Astrodevil** [comment]
Same project exists, You can work on something different.
