### ISSUE TITLE
Recipe App

### ISSUE THREAD

**Issue by shrey2003** [ZeroOctave/ZeroOctave-Javascript-Projects#661]
**Is your feature request related to a problem? Please describe.**
Finding new recipes everyday is a tedious task

**Describe the solution you'd like**
Therefore I have made a website using ReactJs which will have some preloaded recipes and the user can also search for new recipes of his/her choice

### Steps Followed✅

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
this type of project already exists, also we don't accept react projects as of now.
