### ISSUE TITLE
Interactive animated login/signup form

### ISSUE THREAD

**Issue by RAHULBAWA777** [ZeroOctave/ZeroOctave-Javascript-Projects#662]
animated login signup form 
 
stack - HTML CSS JS

 screenshot - 
![image](https://user-images.githubusercontent.com/91609324/168652709-7cae93cc-4764-44bd-baa5-82eeddecccaa.png)

**Comment by Astrodevil** [comment]
check the login/signup page which already exists in the repo,  If the project is similar try to enhance that.

**Comment by sreelakshmig009** [comment]
Closing it as a similar project exists. @RAHULBAWA777 you could try working on a new issue
