### ISSUE TITLE
"Tic Tac Toe" Not working

### ISSUE THREAD

**Issue by SachinMittal1766** [ZeroOctave/ZeroOctave-Javascript-Projects#663]
**Describe the bug**
Tic Tac Toe game shows "Draw" even user wins.

**Expected behavior**
1.  It should show win or lose
2. Should end when user or computer wins.

**Screenshots**
![Screenshot (1049)_LI](https://user-images.githubusercontent.com/82721772/168732720-2c6d5cf2-9775-43ff-b940-080b5ccacd09.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [ ] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by MahendraBishnoi29** [comment]
can i take this issue?

**Comment by Astrodevil** [comment]
> can i take this issue?

It's already assigned to someone else.
