### ISSUE TITLE
Binary to Decimal Converter and vice-versa Webpage

### ISSUE THREAD

**Issue by Sukriti-m** [ZeroOctave/ZeroOctave-Javascript-Projects#665]
**Is your feature request related to a problem? Please describe.**

Binary to Decimal Converter and vice-versa Webpage

**Describe the solution you'd like**

I will add the webpage in which the user can enter the binary value and on clicking the button, the user will receive decimal value and vice-versa.

**Describe alternatives you've considered**
.

**Additional context**

I am contributor at GSSoC '22. Please assign this issue to me.
@Astrodevil 

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
#268
