### ISSUE TITLE
Mern based login page with google authentication

### ISSUE THREAD

**Issue by Sushmita1111** [ZeroOctave/ZeroOctave-Javascript-Projects#670]
I would like to create a mern-based login page that has google authentication and features like forgot password etc. Please assign me this task under GSSOC'22.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Is your feature request related to a problem? Please describe.
- [ ✓] Describe the solution you'd like
- [ ✓] Describe alternatives you've considered
- [ ✓] Additional context

### Code of Conduct✅
- [ ✓] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ ✓] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ ✓] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
check  #651
