### ISSUE TITLE
Github profile not working

### ISSUE THREAD

**Issue by sur16-cse** [ZeroOctave/ZeroOctave-Javascript-Projects#694]
**Describe the bug**
Github profile not working after putting input it will not show desired output

**Expected behavior**
![chrome-capture-2022-4-23 (1)](https://user-images.githubusercontent.com/67889306/169846084-8abf2666-e115-4d98-a194-b8b068ad04e4.gif)

**Screenshots**
![chrome-capture-2022-4-23](https://user-images.githubusercontent.com/67889306/169845940-e7addb2e-d1ee-4cdf-995e-f2f640a4b7d6.gif)

**Desktop :**

**Additional context**
I'm a gssoc contributor.
so kindly assign this issue to resolve the profile of that application

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sur16-cse** [comment]
Dear mentors there is three dot folder in your project structure which hang my pc so is there any way mentor to get rid off and even it cant be deleted easily

**Comment by Astrodevil** [comment]
Nothing is visible to me. Clone again, some issue is from your side.
