### ISSUE TITLE
Add your web dev projects

### ISSUE THREAD

**Issue by NOiR-07** [ZeroOctave/ZeroOctave-Javascript-Projects#71]
Hey! Welcome to our repo, here you can contribute by adding your projects or by contributing to existing projects

While adding new projects make sure to check the pattern followed in the repo for HTML, CSS and JS files.

For e.g
Html files should be added in public folder with name .html
CSS files should be added in assets/css with name .css
JS files should be added in assets/Js with name .js (If available)

Make sure to attach a gif/ss showcasing your project

**Create a new issue for adding projects**

**Comment by tarce09** [comment]
I have added a pull request of a resume builder i made using vanilla JS

**Comment by tarce09** [comment]
is it ok if i add more projects or is there a limit that i can add only one project ?
