### ISSUE TITLE
Word Search 

### ISSUE THREAD

**Issue by sur16-cse** [ZeroOctave/ZeroOctave-Javascript-Projects#712]
**Describe the bug**
Image on website not appearing

**Expected behavior**
Want to fix this issue so that image reflect and looks good

**Screenshots**
![image](https://user-images.githubusercontent.com/67889306/170420205-3748af78-e523-469f-9a9f-653ac8e631ef.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I'm a gssoc contributor kindly assign this issue

### Steps Followed✅

- [x] Describe the bug
- [x] Expected behavior
- [x] Screenshots
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sur16-cse** [comment]
I resolved this issue mentor and requesting from so long label this please still requesting label the pr that u closed

**Comment by sur16-cse** [comment]
I did not get points of this issue please kindly look over that please

**Comment by Astrodevil** [comment]
Labeled now, Sorry for the delay.
