### ISSUE TITLE
Would like to add height converter project

### ISSUE THREAD

**Issue by Ranjana550** [ZeroOctave/ZeroOctave-Javascript-Projects#722]
Heyy @Astrodevil,
Can I add a height converter project?
If yes, I would like to work on this issue.
 I am a GSSOC'22 participant, Kindly assign it to me. 

![image](https://user-images.githubusercontent.com/71266173/170517084-c8e512ae-9d2c-4d01-8a5b-658da9fe66d0.png)

Thank you! :)

**Comment by Astrodevil** [comment]
It already exists.
