### ISSUE TITLE
Spotify clone website

### ISSUE THREAD

**Issue by Areebah03** [ZeroOctave/ZeroOctave-Javascript-Projects#724]
**Describe the solution you'd like**
I want to add a project on spotify clone website. It gives option to play different songs, we can pause or play the songs or skip to next song as we like. Please assign it to me @Astrodevil 

**Additional context**
It is build using html, css, javascript.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the solution you'd like
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### Screenshots
![ss1](https://user-images.githubusercontent.com/85051124/170528369-2518fb80-167a-4449-8684-1d536e75e57d.png)

**Comment by Astrodevil** [comment]
It exists
