### ISSUE TITLE
Fully responsive education website

### ISSUE THREAD

**Issue by Areebah03** [ZeroOctave/ZeroOctave-Javascript-Projects#726]
**Describe the solution you'd like**
I want to add a fully responsive education website.  Please assign it to me @Astrodevil 

**Additional context**
It is build using html and css.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the solution you'd like
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

### Screenshots

![ss3](https://user-images.githubusercontent.com/85051124/170531566-625bd6ed-0427-4d88-9ed2-b78590b359a7.png)

**Comment by Astrodevil** [comment]
https://github.com/khushi-purwar/WebDev-ProjectKart/issues/1407


you are doing same plagiarized contribution under gssoc for different org. I will remove tags from every plagiarized work in the last 2 days of program. keep check of that.

**Comment by Areebah03** [comment]
Okay @Astrodevil I will take care :(
