### ISSUE TITLE
Football website

### ISSUE THREAD

**Issue by aaryahjolia** [ZeroOctave/ZeroOctave-Javascript-Projects#727]
I want to add a football website built from html, css and js.

Screenshot : 

![image](https://user-images.githubusercontent.com/82600388/170534370-4bc60df8-8b2d-4c9f-9c92-10092f29ff3c.png)

**Comment by aaryahjolia** [comment]
@Astrodevil Please assign

**Comment by Astrodevil** [comment]
[??](https://github.com/khushi-purwar/WebDev-ProjectKart/tree/b36fc2708197b51127ac126ef5bd1ea2d4691f4e/Barcelona%20Football%20Website)

We will remove tags from plagiarized work. Please don't do this for the sake of points.
