### ISSUE TITLE
Loruki landing page

### ISSUE THREAD

**Issue by aaryahjolia** [ZeroOctave/ZeroOctave-Javascript-Projects#729]
I want to add a Loruki landing page.

Screenshot : 

![image](https://user-images.githubusercontent.com/82600388/170535193-82b99e2c-a858-4eb2-8bab-7c39cc0e748f.png)

**Comment by aaryahjolia** [comment]
@Astrodevil please assign

**Comment by Astrodevil** [comment]
You are also a contributor of GSSoC in other projects. Check [this](https://github.com/khushi-purwar/WebDev-ProjectKart/pull/768)

plagiarized contributions will not be counted
