### ISSUE TITLE
Draggable Navigation bar

### ISSUE THREAD

**Issue by dheerajrao20** [ZeroOctave/ZeroOctave-Javascript-Projects#731]
**Is your feature request related to a problem? Please describe.**
In modern web dev we need some modern things and obviously crazy too. So I want to add a draggable navbar into the project.
You can drag it throughout your webpages and open the navbar like a box.

**Additional context**
I had made this sometimes before and have the source code right now.
Kindly assign this issue to me so that I can add it as soon as possible

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

@Astrodevil @jeevanalok @Pradumnasaraf @nouraan-ahmed @pranjay-poddar  Kindly assign this issue to me

**Comment by Astrodevil** [comment]
Share screenshots, of what you want to contribute. may be similar project exists.
