### ISSUE TITLE
Want to change title of Animated Portfolio.

### ISSUE THREAD

**Issue by DeveloperAshish8** [ZeroOctave/ZeroOctave-Javascript-Projects#736]
**Describe the bug**
The title of Animated portfolio is displaying as Document.

**To Reproduce**
1. Go to  Animated porfolio page.
2. look at the title.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [X] Describe the bug.
- [X] To Reproduce.
- [X] Expected behavior.
- [X] Additional context.

### Code of Conduct✅
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [X] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by DeveloperAshish8** [comment]
I am a gssoc participant please assign me this issue.

**Comment by Astrodevil** [comment]
This will not be counted in gssoc.
