### ISSUE TITLE
Restaurant site

### ISSUE THREAD

**Issue by vedsom** [ZeroOctave/ZeroOctave-Javascript-Projects#742]
---
name: Feature request
about: Suggest an idea for this project
title: 'Restaurant site'
labels: ''
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
It will for a small community of people such as school, colleges, office etc

**Describe the solution you'd like**
Want to create a restaurant site , which will takes the order and can also book the table

**Additional context**
![sign in - Google Chrome 28-05-2022 04_08_29](https://user-images.githubusercontent.com/96954912/170797237-e50ce3fd-ffc9-4943-baf9-7c68ed77ba6b.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Nothing new. it already exists/
