### ISSUE TITLE
Medical website UI design

### ISSUE THREAD

**Issue by VaishnaviMandloi** [ZeroOctave/ZeroOctave-Javascript-Projects#765]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
I want to add a medical website UI design 

**Describe the solution you'd like**
Home Page to a medical website from which consist of navigation bar and search option and different function

**Describe alternatives you've considered**

**Additional context**
I'm a GSSOC'22 contributor please assign this to me 

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by VaishnaviMandloi** [comment]
Can I open a pr for this as merging of pr are extended till 2 June

**Comment by VaishnaviMandloi** [comment]
> @Astrodevil Can I please open a pr for this as merging of pr are extended till 2 June .
@Astrodevil if possible please allow me to do so

**Comment by Astrodevil** [comment]
Go ahead

**Comment by VaishnaviMandloi** [comment]
![Screenshot_20220601-154054_Discord](https://user-images.githubusercontent.com/98760492/171381221-2520d8c6-5e64-469d-8bab-e155c01b758e.jpg)
@Astrodevil  I get it from here ...
Yes please confirm and if they are not allowed then tell me know too please. 
And thank you so much ...

**Comment by Astrodevil** [comment]
Date extended only for unmerged PR. 

We can't add labels now to new PR.

You can contribute in our repo even after the gssoc.

**Comment by VaishnaviMandloi** [comment]
@Astrodevil ... Okay , I really enjoy contributing to your repo and thank you for all the help and guidance.
