### ISSUE TITLE
#118 Quiz App

### ISSUE THREAD

**Issue by aintcyborg** [ZeroOctave/ZeroOctave-Javascript-Projects#789]
I propose changes to https://zerooctave.github.io/ZeroOctave-Javascript-Projects/Public/Quiz_app.html 
It's UI, The result generated seems quite to be inappropriate, I would like to contribute for the same!

**Comment by Astrodevil** [comment]
Go Ahead

**Comment by aintcyborg** [comment]
I've **commited.**..one pr gave me the following error:" resource-not-accessible-by-integration"...so i closed and reopened...kindly check!
