### ISSUE TITLE
Want to Add a Project of Mine in the Website

### ISSUE THREAD

**Issue by vish-han** [ZeroOctave/ZeroOctave-Javascript-Projects#794]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to add a project of mine in the website so other can also learn from it.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Is your feature request related to a problem? Please describe.
- [x ] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x ] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Read contributing guidelines and add your projects in repo before adding it to Website.

**Comment by vish-han** [comment]
Ok thanks i will add in the repo

**Comment by shreyashkr17** [comment]
Can I also add any proper project of mine which can help other student to learn?

**Comment by Astrodevil** [comment]
> Can I also add any proper project of mine which can help other student to learn?

sure.

**Comment by shreyashkr17** [comment]
ok thanks sir for your approval

**Comment by manmohan4142** [comment]
please accept my pr i have created a javascript project  @Astrodevil 
pr link : https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/pull/925
