### ISSUE TITLE
Fully responsive and professionally designed navbar

### ISSUE THREAD

**Issue by tarce09** [ZeroOctave/ZeroOctave-Javascript-Projects#80]
This navbar is going to be useful responsive and unique and also ui and ux friendly as it is designed and then implemented
![Screenshot_1](https://user-images.githubusercontent.com/69902705/135710409-53c07f5c-e803-4519-af39-4af1782182ab.png)
![Screenshot_2](https://user-images.githubusercontent.com/69902705/135710411-ed151374-f552-46f5-bf63-eeb043f0ec7e.png)

**Comment by Astrodevil** [comment]
Go! Ahead🚀 Follow order of directory and mention this issue in PR

**Comment by tarce09** [comment]
will this not be included in the hacktober fest as i dont see any hacktober tag in the issue ?

**Comment by Astrodevil** [comment]
You have to mention that, while raising issue
