### ISSUE TITLE
Add Guides/Docs to existing projects [SSOC]

### ISSUE THREAD

**Issue by Krishna-bansall** [ZeroOctave/ZeroOctave-Javascript-Projects#801]
**Is your feature request related to a problem? Please describe.**
Well the motive of this project is to teach people about web dev although this project just contains these projects without any sort of guide which is useless to a newbie 

**Describe the solution you'd like**
Add Readme Guides to all projects and render the readme on public site using something like Jekyll 

**Describe alternatives you've considered**
We could've added comments to the code but that would way more work and less intuitive for users

**Additional context**
Whenever user clicks on the project (on public site) instead of redirecting to project itself user should be redirected to the readme 

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Great Suggestion. Explain how are you planning to implement in previous projects. Adding Readme in new projects will be easy.

**Comment by Krishna-bansall** [comment]
Well documenting all the projects would be almost impossible 

But we can document 10-20 good projects because honestly some of the projects are pretty bad & not worth documenting 

I can build the md rendering functionality  myself and build some templates so that we can open issues with beginner friendly tags so people coming from ssoc can get started by documenting

**Comment by Astrodevil** [comment]
Cool, It Will be better if all readme will be put in a docs folder inside assets to avoid mixing. And it will be fetched on main page from there. 

Go ahead👍

**Comment by Krishna-bansall** [comment]
Ok sure I'll create a new project documentation guide & a guide for documentation of old ones

Ok so you assign this issue to me 

I'll pick some projects that should be good to document first and should i raise multiple issues for those? So that you can label them as low hanging fruits?
