### ISSUE TITLE
Adding a new project to the website

### ISSUE THREAD

**Issue by vandana3869** [ZeroOctave/ZeroOctave-Javascript-Projects#804]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
I want to add my project - Simon Game,  Its beginner a friendly  project
that would help in improving JavaScript skills.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the solution you'd like

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
It's already there.
