### ISSUE TITLE
Adding a Day-Night Toggle Button

### ISSUE THREAD

**Issue by vandana3869** [ZeroOctave/ZeroOctave-Javascript-Projects#805]
**Is your feature request related to a problem? Please describe.**
As a programmer, I prefer dark mode because it is more comfortable for eyes.

**Describe the solution you'd like**
I would like to add one button for switching between dark and light mode.

**Additional context**
![image](https://user-images.githubusercontent.com/84574563/183096886-4d43de76-5406-4eed-8495-6b4424cca8d6.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like

- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Astrodevil** [comment]
Irregularities in color effect when hover over AM and PM after sliding toggle. Fix it.
