### ISSUE TITLE
"Wordle Clone" not working/ taking input [SSOC]

### ISSUE THREAD

**Issue by ShivanshAr97** [ZeroOctave/ZeroOctave-Javascript-Projects#816]
**Describe the bug**
Wordle clone is not taking the input from the user.

**To Reproduce**
1. Go to 'https://zerooctave.github.io/ZeroOctave-Javascript-Projects/Public/Wordle-clone.html'
2. User not able to enter letters to form the word.

**Expected behavior**
User should be able to enter letters and thus able to make words and play the game.

**Screenshots**

![image](https://user-images.githubusercontent.com/96040322/183261198-d514fca0-22fb-46d1-bff1-75ece6210e4f.png)
Unable to provide input.

**Desktop (please complete the following information):**
 Windows
Chrome
-

**Smartphone (please complete the following information):**
Redmi 9
Chrome

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Atharv-110** [comment]
@ShivanshAr97 It is taking input from the onscreen keyboard but not from our machine's keyboard. Go for it and fix this bug.
Assigned to you!
All the best.
