### ISSUE TITLE
candy store website not working

### ISSUE THREAD

**Issue by Rancho2002** [ZeroOctave/ZeroOctave-Javascript-Projects#821]
![Screenshot (71)](https://user-images.githubusercontent.com/92109154/183814942-f70d2eeb-a991-43cf-a484-6711601f67fc.png)
The file and folder are not placed in the right place in GitHub that's why the candy store website not opening. Let me fix this issue.
[SSOC] 
Here is the link: https://zerooctave.github.io/ZeroOctave-Javascript-Projects/Public/Candy
@Astrodevil  @NOiR-07  @sreelakshmig009

**Comment by myhacktech** [comment]
@Rancho2002 i am closing this issue as it was created 8 days ago by someone else
