### ISSUE TITLE
Gym website (project 91) navbar not working [SSOC]

### ISSUE THREAD

**Issue by ravish036** [ZeroOctave/ZeroOctave-Javascript-Projects#824]
**Describe the bug**

Navigation bar of the Fitness time website in non-functioning. 

**Expected behavior**
Navbar should take us to the particular section of the webpage just by a click. 

**Screenshots**
![image](https://user-images.githubusercontent.com/84343005/183308734-6f47f9b3-be8e-4bd0-bf9d-22c36af44c8d.png)
In the above screenshot, the navigation bar you can see is just giving you an information about the home page section the webpage & on clicking on other section its not functioning properly.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ x] Describe the bug
- [ ] To Reproduce
- [ x] Expected behavior
- [ x] Screenshots
- [ ] Additional context

### Code of Conduct✅
- [ x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by ayush-wd** [comment]
Hi, I am a front end developer. I can work on this issue #824

**Comment by Atharv-110** [comment]
> I will work on this issue please assign this issue to me.

@satyamkale27 this issue is created by someone else so it will be assigned to them. First Come First Serve Basis
You can create some different issues.
Thank you

**Comment by Atharv-110** [comment]
> **Describe the bug**
> 
> Navigation bar of the Fitness time website in non-functioning.
> 
> **Expected behavior** Navbar should take us to the particular section of the webpage just by a click.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/84343005/183308734-6f47f9b3-be8e-4bd0-bf9d-22c36af44c8d.png) In the above screenshot, the navigation bar you can see is just giving you an information about the home page section the webpage & on clicking on other section its not functioning properly.
> 
> ### Steps Followed✅
> Check the box with [x] If you followed all the steps.
> 
> * [ x] Describe the bug
> * [ ]  To Reproduce
> * [ x] Expected behavior
> * [ x] Screenshots
> * [ ]  Additional context
> 
> ### Code of Conduct✅
> * [ x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
> * [ x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
> * [ x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

Yes, @ravish036 Go for it. Assigned to you.
All the best.

**Comment by satyamkale27** [comment]
> > I will work on this issue please assign this issue to me.
> 
> @satyamkale27 this issue is created by someone else so it will be assigned to them. First Come First Serve Basis You can create some different issues. Thank you

i have already made pull request and fixed issue please rewiew my code
