### ISSUE TITLE
Custom Video Player

### ISSUE THREAD

**Issue by tarunbisht-24** [ZeroOctave/ZeroOctave-Javascript-Projects#828]
**Is your feature request related to a problem? Please describe.**

-I want to add a new project namely Custom Video Player. It's an HTML, CSS, and Javascript project. Please assign me this issue under SSOC'22 tag.

**Describe the solution you'd like**
-A user can loop through the whole video according to its choice I have created two buttons to skip the video 10s backward or forward, you can also slide through the whole video and increase or decrease its playback speed, etc.

**Describe alternatives you've considered**
-Another feature could be making subtitles and playback the video from where the user has left it.

**Additional context**

![customvideoplayer](https://user-images.githubusercontent.com/77788209/183439757-69188fc4-65f4-42f4-ab2e-5fe7d3c0759e.jpeg)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through the project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Sandhya312** [comment]
@tarunbisht-24  Hey, If you are an SSOC'22 contributor then properly add the SSOC tag.

**Comment by tarunbisht-24** [comment]
@Sandhya312 edited the comment, pls check again and tag it undrer the SSOC tag and assign me this issue to work on.

**Comment by KushagraTomar** [comment]
Custom Video Player #828
pls assign this to me

**Comment by Sandhya312** [comment]
@tarunbisht-24 Done. Go ahead.
