### ISSUE TITLE
Report Calculator not working[SSOC]

### ISSUE THREAD

**Issue by sumeetk10** [ZeroOctave/ZeroOctave-Javascript-Projects#830]
**Describe the bug**
Calculate button is not clickable(not working) and there is not option to display result.

**To Reproduce**
1. Go to 'Report Calculator'
2. Enter the 'Marks'
3. Click on 'Calculate'

**Expected behavior**
Upon clicking the calculate button it should give the precentage scored, on a separate textbox.

**Screenshots**
![Screenshot 2022-08-08 161108](https://user-images.githubusercontent.com/81513463/183587784-4ba1226f-085e-4543-8dad-e3971ab094a8.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [104.0.5112.81]

**Smartphone (please complete the following information):**
 - Device: [Redmi 8 Pro]
 - OS: [Android 11]
 - Browser [chrome]
 - Version [104.0.5112.79]

**Additional context**
I can improve the overall UI of webpage.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Yuvraj102** [comment]
@sumeetk10 
assign me the issue
