### ISSUE TITLE
2D Breakout Game Project [SSOC]

### ISSUE THREAD

**Issue by KushagraTomar** [ZeroOctave/ZeroOctave-Javascript-Projects#831]
Is your feature request related to a problem? Please describe.
- It's an HTML, CSS, and Javascript project. Please assign me this issue under SSOC tag.

Describe the solution you'd like
- The player can move horizontally and the ball can move in any direction and will hit the bricks and the score will increase

Describe alternatives you've considered
- Another thing that can be added is that each brick will have different points and speed will increase as the time inceases

Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ]  Is your feature request related to a problem? Please describe.
- [ ]  Describe the solution you'd like
- [ ]  Describe alternatives you've considered
- [ ]  Additional context

Code of Conduct✅
- [ ] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ ]  I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ ]  I have gone through project

**Comment by KushagraTomar** [comment]
pls assign this to me I am still waiting

**Comment by Astrodevil** [comment]
Is this the same as #187 ?

**Comment by KushagraTomar** [comment]
@Astrodevil it would be more graphic rich and with more functionality
