### ISSUE TITLE
Modify tip calculator

### ISSUE THREAD

**Issue by kakkarot0** [ZeroOctave/ZeroOctave-Javascript-Projects#832]
**Is your feature request related to a problem? Please describe.**
I would like to change the  UI of tip calculator. Please assign me this issue under SSOC'22 tag.

**Describe the solution you'd like**
First the good background is must to make this attractive and  I was thinking of giving different section for Bill amount, tip percentage and this will display total Billed customer needs to pay.

**Describe alternatives you've considered**
Another feature can be using more JavaScript.

**Additional context**
![image](https://user-images.githubusercontent.com/94862104/183611607-4a022b38-45c0-4512-8352-46d20eeb8d2d.png)

I'm planning on using this extra white space portion.

###Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ✅] Is your feature request related to a problem? Please describe.
- [ ✅] Describe the solution you'd like
- [✅ ] Describe alternatives you've considered
- [ ✅] Additional context

###Code of Conduct✅
- [ ✅] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ ✅] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [✅ ] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Rancho2002** [comment]
Please assign the task to me
