### ISSUE TITLE
The image of "Maze Game" is invisible

### ISSUE THREAD

**Issue by zugzwang03** [ZeroOctave/ZeroOctave-Javascript-Projects#839]
**Describe the bug**
The image of "Maze Game" is not visible

**To Reproduce**
1. Go to 'search bar'
2. Click on 'search bar' or search "Maze Game"
3. Scroll down to 'Maze Game'

**Expected behavior**
I want put the correct image in place

**Screenshots**
![maze](https://user-images.githubusercontent.com/95460021/184400328-dc3a5717-fb57-4a6f-9341-028f6c0e442a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I want to resolve this issue under SSOC'22.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by deeproop** [comment]
Hello, @Astrodevil I have created a pull request for this issue, hope it resolves the problem :)
