### ISSUE TITLE
Static Buttons on Drum Kit project [SSOC]

### ISSUE THREAD

**Issue by sumeetk10** [ZeroOctave/ZeroOctave-Javascript-Projects#846]
**Is your feature request related to a problem? Please describe.**
In Drum Kit project, buttons are not clickable thus does not give any sound effect.

**Describe the solution you'd like**
I would like to add clickable buttons upon clicking which a sound generates.

**Describe alternatives you've considered**
It would be almost similar to piano buttons.

**Additional context**
![Screenshot 2022-08-17 204236](https://user-images.githubusercontent.com/81513463/185176937-5c6db381-39b9-426a-ae61-e4f726e64168.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by deeproop** [comment]
Will you please provide the site link, not able to find this project on the site.

**Comment by sumeetk10** [comment]
https://zerooctave.github.io/ZeroOctave-Javascript-Projects/Public/drum_kit.html

**Comment by deeproop** [comment]
Hello @sumeetk10, I have created a pull request for this issue, it will solve the problem in the drum kit project :)

**Comment by deeproop** [comment]
@Astrodevil kindly review the PR.
