### ISSUE TITLE
Happy Hacktober project not working[SSOC]

### ISSUE THREAD

**Issue by Manish5121** [ZeroOctave/ZeroOctave-Javascript-Projects#847]
**Describe the bug**

- Happy Hacktober project (number 95 in the project list) is not functioning. [SSOC]

**Screenshots**

![hactober fest issue](https://user-images.githubusercontent.com/94914243/185335314-b5ca22d8-40be-4c61-97b9-494064be7263.png)

- The issue is due to simple typo in the code file, you can see in the images that the message.html file is not loading
 ![hactober fest issue ss 3](https://user-images.githubusercontent.com/94914243/185336256-5430cce2-0bd5-4d39-8262-0c392ff2afc2.png)

- the file name should be `message.html`  not `Message.html` the letter "m" should be lower-case.
![hactober fest issue ss 2](https://user-images.githubusercontent.com/94914243/185336181-89b83044-3162-4256-91e5-7ec5212a48c8.png)

-please assign this issue so which it can be solved 

**To Reproduce**

1. Go to 'https://zerooctave.github.io/ZeroOctave-Javascript-Projects/Public/happy_hacktober/happyhactober.html'
2. Enter your name
3. Click on 'submit'

**Expected behavior**
- after entering your name and clicking on submit a new page should open which will wish you happy hacktober

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Smartphone (please complete the following information):**
 - Device: Poco X2
 - chrome

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by sumeetk10** [comment]
Hello @Manish5121 I am already working on this issue.

**Comment by Manish5121** [comment]
Ohh sorry i didn't see that..

**Comment by rathi710** [comment]
i can resolve this issue. Assign it to me
