### ISSUE TITLE
I wish to make a music app using html/css/js

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [ZeroOctave/ZeroOctave-Javascript-Projects#85]
The music app is going be good and fully responsive.

![Music](https://user-images.githubusercontent.com/72568715/135715598-da5845b2-cb66-4dda-b19c-799677b96a92.PNG)

**Comment by Astrodevil** [comment]
@Sulagna-Dutta-Roy Tap music project is already there in this repo.
