### ISSUE TITLE
Weight converter site is not working

### ISSUE THREAD

**Issue by sumeetk10** [ZeroOctave/ZeroOctave-Javascript-Projects#867]
**Describe the bug**
Weight Converter site is static, it is not doing any function.

**To Reproduce**
1. Go to 'Weight Converter'
2. Enter weight
3. Select from dropdown

**Expected behavior**
Upon filling the certain weight it should produce the result in desired unit.

**Screenshots**
![Screenshot 2022-08-28 224551](https://user-images.githubusercontent.com/81513463/187086534-60a6ce96-5984-4ea2-b3aa-71f945787869.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]
 - Version [108]

**Additional context**
There is on clickable button for calculate

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by newbie2508** [comment]
Is this issue still open? Can i work on it, if no one is working on it? @myhacktech

**Comment by newbie2508** [comment]
Can I work on it? @myhacktech
