### ISSUE TITLE
Correcting Navigation bar of Youtube clone + tags tiles of it

### ISSUE THREAD

**Issue by Kuldeepmishra28** [ZeroOctave/ZeroOctave-Javascript-Projects#890]
**Is your feature request related to a problem? Please describe.**
Wish to enhance the navigation bar of the clone and the recommendation tag tiles of the page

**Describe the solution you'd like**
Changing it to the original UI of what Youtube is.

**Describe alternatives you've considered**
Changing the structure of the HTML tags and with proper utilization of CSS will fix it.
**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by kumarsanu2002** [comment]
let me know if i could do anything.

**Comment by Satyabrat-Ojha** [comment]
Please assign this issue to me under "hacktoberfest" label.

**Comment by Anmol-Baranwal** [comment]
@Kuldeepmishra28 
Would you work on this issue? If not, I would like to close this.

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me

**Comment by Anmol-Baranwal** [comment]
@subhamkumarr 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.
