### ISSUE TITLE
Improving UI of Color Code Converter

### ISSUE THREAD

**Issue by rtewari056** [ZeroOctave/ZeroOctave-Javascript-Projects#895]
**Is your feature request related to a problem? Please describe.**
The UI of Color Code Converter can be improved for better user experience.

**Describe the solution you'd like**
I will add custom styles to make the UI look better for users.

**Describe alternatives you've considered**
I want to improve the UI by styling button, background, input fields, etc. 

**Additional context**
Right now the UI is looking like this

![color code](https://user-images.githubusercontent.com/75976169/192295043-8b58b78b-8c3a-4310-b746-2adfb4841389.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by rtewari056** [comment]
I want to make this contribution under SSOC'22

**Comment by sanjana2417** [comment]
I can improve the UI in a better way. Can I be assigned with the same?

**Comment by Anmol-Baranwal** [comment]
@sanjana2417 
Do you want to work on this issue?

**Comment by rtewari056** [comment]
@Anmol-Baranwal You can close this issue
