### ISSUE TITLE
I wish to add more buttons in Calculator

### ISSUE THREAD

**Issue by aditya-464** [ZeroOctave/ZeroOctave-Javascript-Projects#901]
**Is your feature request related to a problem? Please describe.**
The calculator does not have buttons for x^2,  x^y, square root of x, and log (x) operations. It is quite frustrating, to write the values of 兀 and e manually.

**Describe the solution you'd like**
I wish to add buttons for  兀 , e,  x^2,  x^y,  square root of x and log (x) operations.

**Describe alternatives you've considered**
I will insert a new column for buttons, and use JavaScript to define their working logic.

**Additional context**
Below is the screenshot of the UI showing the new buttons.

![Screenshot (695)](https://user-images.githubusercontent.com/96364363/193057011-91b125b6-134b-4b07-aaea-a49ee29b6412.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Please assign this issue to me under "hacktoberfest" label.**

**Comment by georgioupanayiotis** [comment]
@aditya-464  can you please assign this to me?

**Comment by aditya-464** [comment]
@georgioupanayiotis  I am a contributor and not a maintainer, so I was actually asking the project maintainers to  assign this issue to me

**Comment by georgioupanayiotis** [comment]
no worries there is enough issues for everyone :P

**Comment by aditya-464** [comment]
@Astrodevil  Please assign this issue #901 to me

**Comment by Satyabrat-Ojha** [comment]
Please assign this issue to me under "hacktoberfest" label.
