### ISSUE TITLE
Improved UI for BMI Calculator

### ISSUE THREAD

**Issue by i-ujjwaljha** [ZeroOctave/ZeroOctave-Javascript-Projects#914]
**Is your feature request related to a problem? Please describe.**
The interface of the BMI calculator looks disarranged and unaligned.

**Describe the solution you'd like**
I would like to restructure the interface to give the user a user-friendly experience.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x ] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by i-ujjwaljha** [comment]
can you assign me this task?

**Comment by rahul0306** [comment]
I can improve the UI of the BMI Calculator and fix the output. Can you assign this issue to me?

**Comment by Anmol-Baranwal** [comment]
@i-ujjwaljha 
Do you want to work on this issue? If not, then I would close this.

**Comment by i-ujjwaljha** [comment]
Yes. I am willing to give this a try.

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me

**Comment by Anmol-Baranwal** [comment]
@subhamkumarr 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by subhamkumarr** [comment]
@Anmol-Baranwal  can you please describe what UI changes I need to do

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal can you please describe what UI changes I need to do

You should do this before getting assigned, nonetheless use the basic UI Design principles to improve the visual appeal. 
I will request the changes once you make a PR.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal Sir I have changed the UI

I will review it till tomorrow. Kindly wait, and I will let you if there any changes needed.

**Comment by subhamkumarr** [comment]
OK @Anmol-Baranwal
