### ISSUE TITLE
Add remove button in Resume Builder

### ISSUE THREAD

**Issue by aditya-464** [ZeroOctave/ZeroOctave-Javascript-Projects#915]
**Is your feature request related to a problem? Please describe.**
In the resume builder website, we can add as many new fields in a particular topic like Education, but what if we add some extra fileds by mistake? There is no way to delete those extra fields and sections, other than starting all over again, which itself is a hectic and tedious process.

**Describe the solution you'd like**
I will add a remove button for each section, so that user can easily add & delete as many fields and sections as he/she wants to. I will also take care, that when the user prints the resume, those remove buttons will not be there.

**Describe alternatives you've considered**
I will add a remove button for each section, which will help to delete their respective fields only.

**Additional context**

Screenshot of UI of resume builder, after adding the remove buttons

![resume_builder](https://user-images.githubusercontent.com/96364363/193448000-e1bf84c6-ff51-490e-8fbc-684c16f6cd79.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by ruchie194** [comment]
hey assign this to me i'll make it more better

**Comment by Astrodevil** [comment]
> hey assign this to me i'll make it more better

go ahead
