### ISSUE TITLE
UI Improvement in Color Game

### ISSUE THREAD

**Issue by amitmishra11** [ZeroOctave/ZeroOctave-Javascript-Projects#916]
**Is your feature request related to a problem? Please describe.**
When we play a game its UI plays a big role in user engagement. So I would like to improve UI of color choosing game

**Describe the solution you'd like**
I would try to improve the UI of the game to make it better.

**Describe alternatives you've considered**
CSS and its frameworks can be used for UI improvement.

**Additional context**
<img width="939" alt="image" src="https://user-images.githubusercontent.com/96818986/193449006-78ed4556-12cc-4cf3-bb92-b0191f20cadf.png">
The game is not very attractive right now,

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [X] Is your feature request related to a problem? Please describe.
- [X] Describe the solution you'd like
- [X] Describe alternatives you've considered
- [X] Additional context

### Code of Conduct✅
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [X] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by amitmishra11** [comment]
Please assign me this issue

**Comment by Anmol-Baranwal** [comment]
According to me, it works fine. If you think that you can make UI much better from existing one. Make a PR and reopen this issue.
For now, I am closing this.
