### ISSUE TITLE
Fix Navbar, Pop-up and number of books in Book Library

### ISSUE THREAD

**Issue by aditya-464** [ZeroOctave/ZeroOctave-Javascript-Projects#917]
**Is your feature request related to a problem? Please describe.**
When we add a book to the list, a pop-up appears which shifts the layout of the website, which is not all pleasing. The number of books is also less. When we scroll down the page, the navbar goes up, which again does not look good.

**Describe the solution you'd like**
I will make the navbar fixed and it's background to be opaque. I will make changes in the layout of the website, such that when pop up appears the layout of website doesn't shift. Also I will add some more options of book types.

**Describe alternatives you've considered**
I will make the navbar fixed and it's background to be opaque. I will make changes in the layout of the website, such that when pop up appears the layout of website doesn't shift. Also I will add some more options of book types.

**Additional context**

Screenshot of UI of Books Library after fixing the pop-up and navbar issue

![book1](https://user-images.githubusercontent.com/96364363/193449142-c328cb50-4301-4120-b896-ba4ff0609495.png)

![book2](https://user-images.githubusercontent.com/96364363/193449148-288aa77d-55df-40be-86a1-294934312e8a.png)

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [x] Describe alternatives you've considered
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by B1TSH3LL** [comment]
hey i would try this fix for you can you please assign it to me ???

**Comment by tejasjaiswal07** [comment]
Hey @aditya-464, please assign this issue to me.
thank you!

**Comment by aditya-464** [comment]
@tejasjaiswal07  I am contributor, not maintainer. I have already resolved this issue.

**Comment by Anmol-Baranwal** [comment]
@aditya-464 
Is the PR merged for this issue, then I would close this. Please mention the PR for confirmation.
