### ISSUE TITLE
add new tower of hanoi game made by me

### ISSUE THREAD

**Issue by shreyashkr17** [ZeroOctave/ZeroOctave-Javascript-Projects#920]

**Comment by Akshatmish** [comment]
I would like to work on this project . please assign it to me

**Comment by Anmol-Baranwal** [comment]
@shreyashkr17 
Are you willing to work on this issue?

**Comment by shreyashkr17** [comment]
Sorry sir i am not into this project.

**Comment by Anmol-Baranwal** [comment]
> Sorry sir i am not into this project.

No worries, thanks for informing me.
