### ISSUE TITLE
Login-form

### ISSUE THREAD

**Issue by sanil011** [ZeroOctave/ZeroOctave-Javascript-Projects#927]
hey i can add form wave animation feature in your login form project.
Please allow me to do this.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

https://user-images.githubusercontent.com/105095685/193910585-a656623d-e367-4b5a-943a-a88582de207b.mov

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ ] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Anmol-Baranwal** [comment]
@sanil011 
Are you willing to work on this issue, if not I would like to close this.

**Comment by Umesh-Meher** [comment]
can i work on this issue

**Comment by Anmol-Baranwal** [comment]
> can i work on this issue

Sure, go ahead. I have assigned you the issue. Feel free to tag me if you need any help :)

**Comment by Umesh-Meher** [comment]
I am sorry . It's my first time. I was unaware that I got assigned to work
on this. Can you please re-assign it .
Can you please give a brief about the problem statement and how I
can  approach.

**Comment by Anmol-Baranwal** [comment]
> I am sorry . It's my first time. I was unaware that I got assigned to work on this. Can you please re-assign it . Can you please give a brief about the problem statement and how I can approach.

@Umesh-Meher 
Once I have assigned you the issue, there are no limitations or deadlines, so there is no need to reassign you the task.

Regarding the approach, you can target the label and utilize CSS properties such as `transition`, `transform`, and `translateX` to achieve the desired output. If you require detailed assistance, please feel free to reply to this message.

**Comment by karantec** [comment]
please  me this issue under gSSOC 2023

**Comment by Anmol-Baranwal** [comment]
> 



> please me this issue under gSSOC 2023

This project is not under GSSoC'23. You can go to https://github.com/ZeroOctave/resource-gallery for contributing

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me

**Comment by Anmol-Baranwal** [comment]
@subhamkumarr 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by Anmol-Baranwal** [comment]
> @Anmol-Baranwal, sir, i have made the required changes, but I am facing an issue with creating a new PR Creating new PR is not visible.
> 
> ![image](https://user-images.githubusercontent.com/99977240/252881527-942977c1-1593-487c-8fc1-8bd8453e6162.png)

Make sure, you create a new branch to work on this. When you will push the changes, you will get a call to action to make a PR on GitHub on your respective branch.

> You can visit [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow) to refer to official docs

**Comment by Anmol-Baranwal** [comment]
@subhamkumarr 
You have pushed those changes in wrong branch. If you are unaware of how to fix the issue, then I suggest removing those changes, and working on 1 issue at a time.
![image](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/74038190/d4ee1f96-6fa6-4981-b980-f10d8f64dce8)

**Comment by subhamkumarr** [comment]
@Anmol-Baranwal I have created a new branch and created PR. Can you please check?

**Comment by Anmol-Baranwal** [comment]
Sorry, but I will not review the PR.

Change these accordingly: as per instructions of the comment.
![image](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/74038190/74a22886-36c1-425c-ae4b-4012f0f40d7e)

You need to link the pr properly to this:
![image](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/assets/74038190/e326e67f-88c6-4a23-bdc6-1042ee33596c)

Last time, I edited myself. But please do these, then I will look at your PR.
