### ISSUE TITLE
Implement toggle button functionality to switch between Analog and Digital clock

### ISSUE THREAD

**Issue by sanil011** [ZeroOctave/ZeroOctave-Javascript-Projects#928]
I can a toggle button like when we click that button changes the theme suppose if clock in light mode then on click buttton theme  will change to dark mode and vice versa.

just like that.

https://user-images.githubusercontent.com/105095685/193912231-59a43571-9983-44f5-bd9b-3b83f6c71348.mov

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by rahul0306** [comment]
![clock](https://user-images.githubusercontent.com/91728958/195077122-3a215d62-4c11-49a0-951d-50735838614e.PNG)
I can create a toggle button to switch to digital clock and vice versa from the above image from the project. Can you please assign this issue to me??

**Comment by Anmol-Baranwal** [comment]
@sanil011 
Are you willing to work on this issue, if not I would like to close this?

**Comment by shreyanukala** [comment]
Can I work on it?

**Comment by Anmol-Baranwal** [comment]
> Can I work on it?

Unfortunately, this particular task has already been addressed in issue #1048. 

However, I encourage you to explore other projects where you can contribute. You can also consider refactoring significant portions of the code. 

Before you start working on any task, it's advisable to create an issue first to ensure that it is worth pursuing.

**Comment by aysal04** [comment]
Can I work on this issue ?

**Comment by Anmol-Baranwal** [comment]
> Can I work on this issue ?

@shreyanukala 

Are you currently working on this? If not, then I would assign this task to Aysal.

**Comment by Anmol-Baranwal** [comment]
@aysal04 
I have assigned you the issue because there has been no response from sheyanukala. You can go ahead and create a pull request (PR), and I will review it. I'm not removing him from the assignees list since he requested it first. So, please make the PR and let me know when you're ready for a review.
