### ISSUE TITLE
Restaurent landing page add some features and changes in ui

### ISSUE THREAD

**Issue by sanil011** [ZeroOctave/ZeroOctave-Javascript-Projects#929]
I can change in Restaurant landing page following-:
- CHANGES IN UI
-ADD SOME CSS ANIMATION
-MAKE SOME CHANGES IN FORM TO LOOK GOOD

PLEASE ALLOW ME THIS ISSUE.

ANIMATION LIKE THIS AND MANY MORE OTHER WHEN WE JUST OPEN PAGE-

https://user-images.githubusercontent.com/105095685/193914082-0171e60e-171a-4eee-8736-46268a4dd98c.mp4

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ X] Is your feature request related to a problem? Please describe.
- [ X] Describe the solution you'd like
- [ X] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [X ] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ X] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [X ] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Anmol-Baranwal** [comment]
@sanil011 
Are you willing to work on this issue, if not I would like to close this?
