### ISSUE TITLE
Update Email Validator.

### ISSUE THREAD

**Issue by surbhi400** [ZeroOctave/ZeroOctave-Javascript-Projects#930]
**Is your feature request related to a problem? Please describe.**
The UI and features of email validator is very bad and I want to fix it as it is very unpleasant to the eyes.

**Describe the solution you'd like**
Improve the UI and features.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x]  I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by surbhi400** [comment]
@Astrodevil please assign me this issue, I would like to work on it.

**Comment by Anmol-Baranwal** [comment]
@surbhi400 
Are you willing to work on this issue, if not I would like to close this?

**Comment by surbhi400** [comment]
@Anmol-Baranwal, I will work on this.

**Comment by Anmol-Baranwal** [comment]
Sure, go ahead. I have assigned you the issue.
> Just read [guidelines](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CONTRIBUTING.md) before contributing.

**Comment by surbhi400** [comment]
@Anmol-Baranwal I have made the PR for this issue. Please check it and let me know if any changes are required.
