### ISSUE TITLE
Hamburger menu 

### ISSUE THREAD

**Issue by ankita-104** [ZeroOctave/ZeroOctave-Javascript-Projects#955]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
This is an interesting style of drop down menu. Can be used in any website to add on to its UI.

I want to do this task so please assign me.

**Describe alternatives you've considered**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Is your feature request related to a problem? Please describe.
- [ ] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [ ] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [ ] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [ ] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by ankita-104** [comment]
This is an interesting style of drop down menu. Can be used in any website to add on to its UI.

I want to do this task so please assign me.

**Comment by Anmol-Baranwal** [comment]
@ankita-104 
Are you willing to work on this issue, if not I would like to close this?
