### ISSUE TITLE
Email link not working

### ISSUE THREAD

**Issue by prakhar-1005** [ZeroOctave/ZeroOctave-Javascript-Projects#959]
The email link in the Follow Us section is not working. Please provide the link to be added.

1. Scroll down to the Follow Us section at the bottom of the page.
2. On clicking the email icon, it shows error.

**Expected behavior**
On clicking the email button it should open the email. 

Screenshots
![Screenshot (41)_LI](https://user-images.githubusercontent.com/94559623/194727886-9c20b559-312c-4d0b-971f-b7f73bb6ac56.jpg)

![Screenshot (42)](https://user-images.githubusercontent.com/94559623/194727888-d9473b1f-571a-42bd-9333-b25e2c11a87d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser: Chrome

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [x] Screenshots

### Code of Conduct✅
- [✅] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [✅] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [✅] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by prakhar-1005** [comment]
Hey @Astrodevil can you please take a look at the issue I raised

**Comment by prakhar-1005** [comment]
@Astrodevil can you please share the Email ID also

**Comment by Mr-krishn** [comment]
i can do this please assign this task to me
