### ISSUE TITLE
Add a URL_Shortner project

### ISSUE THREAD

**Issue by madhhuurrii** [ZeroOctave/ZeroOctave-Javascript-Projects#968]
**Is your feature request related to a problem? Please describe.**
I want to contribute our group's URL_Shortner project to this repository as a part of our coursework for OpenSource Lab

**Describe the solution you'd like**
Our project provides short url for long one

**Additional context**
Project Link: https://github.com/madhhuurrii/URL-Shortner

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [ ] Is your feature request related to a problem? Please describe.
- [x] Describe the solution you'd like
- [ ] Describe alternatives you've considered
- [ ] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by Anmol-Baranwal** [comment]
@madhhuurrii 
Are you willing to work on this issue, if not I would like to close this?
> The project to be merged should be made using HTML, CSS, JavaScript & not frameworks.

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me

**Comment by Anmol-Baranwal** [comment]
@subhamkumarr 
I have assigned you the issue. Please proceed with it, and don't hesitate to tag me if you require any assistance.

**Comment by ShreeveshKumar** [comment]
I have made this project should i pull the pr ??

**Comment by Anmol-Baranwal** [comment]
Sure, I will review this whenever I get time.
