### ISSUE TITLE
Dark mode button not Working

### ISSUE THREAD

**Issue by Ayushhgupta39** [ZeroOctave/ZeroOctave-Javascript-Projects#973]
When toggling the AM/PM dark mode button, it doesn't have any affect.

After fixing the issue, The dark mode will keep the site as it is, but the light mode will change the theme to white color.

![Screenshot (21)](https://user-images.githubusercontent.com/96309609/195269773-2676fdfa-b3f0-4d43-8f74-bb1359c04c6d.png)
![Screenshot (22)](https://user-images.githubusercontent.com/96309609/195269793-642ae72c-26c5-456c-a556-de171abcf9e8.png)

**Comment by Omkar-2003** [comment]
Could you assign this issue to me ?

**Comment by cybraia** [comment]
HI, is the issue resolved? If not, could you please assign it to me? Thanks!
