### ISSUE TITLE
Dark mode for Analog Clock

### ISSUE THREAD

**Issue by undextered** [ZeroOctave/ZeroOctave-Javascript-Projects#976]
Hey there, I have created a dark mode toggle for the analog clock. Check it OUT.
![ASTRO Javascript Clock UI Dark - Google Chrome 2022-10-14 16-54-10](https://user-images.githubusercontent.com/76005012/195836405-cc44b9f4-ec12-4f98-a3b1-c8addd34ba72.gif)

**Comment by Anmol-Baranwal** [comment]
@Astrodevil 
Should I close this issue? Or ask author of issue to work on this.

**Comment by Astrodevil** [comment]
Go ahead @undextered If you can.

**Comment by aysal04** [comment]
I have added the dark mode feature. Could you please review it?
