### ISSUE TITLE
CSS Animation Project

### ISSUE THREAD

**Issue by Dimple-Choudhary** [ZeroOctave/ZeroOctave-Javascript-Projects#985]
## CSS Animation Project 

Bouncing Ball Animation CSS.
CSS magic line Icon fill hover effect.
Responsive ecommerce product card design vanilla tilt.js.
frosted Glass scratch out effect.

**Please @Astrodevil  assign me this issue .Under Hacktoberfest 2022

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by aankitasoni** [comment]
Will you please assign this project to me as I am interested to work on this. @Dimple-Choudhary
