### ISSUE TITLE
Audio feature not working in Dictionary app

### ISSUE THREAD

**Issue by getRicha** [ZeroOctave/ZeroOctave-Javascript-Projects#986]
**Describe the bug**
The app is unable to provide audio for some searched words.

**To Reproduce**
1. Go to the dictionary app
2. Search for a word, say weather
3. No audio is heard on clicking the speaker icon
4. See the error in console

**Expected behavior**
On clicking the speaker button, audio should be heard pronouncing the searched word.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 106.0.5249.119

**Additional context**
Please assign this issue to me under Hacktoberfest.

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x] Describe the bug
- [x] To Reproduce
- [x] Expected behavior
- [ ] Screenshots
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by aankitasoni** [comment]
please assign this to me. @getRicha

**Comment by getRicha** [comment]
Hey @aankitasoni, I am a contributor and not a maintainer. I was actually asking the project maintainers to assign this issue to me.

**Comment by getRicha** [comment]
@Astrodevil kindly review the PR.
