### ISSUE TITLE
Want to correct typos in Gym Website and Add meaningful text at some places.

### ISSUE THREAD

**Issue by rajuljha** [ZeroOctave/ZeroOctave-Javascript-Projects#994]
**Describe the bug**
There are typos in two headings in Gym Website and dummy text under health, cardio, body, fitness sub-headings. I want top make it more meaningful. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 106.0

**Smartphone (please complete the following information):**

**Additional context**

### Steps Followed✅
Check the box with [x] If you followed all the steps.

- [x ] Describe the bug
- [ ] To Reproduce
- [ ] Expected behavior
- [ ] Screenshots
- [x] Additional context

### Code of Conduct✅
- [x] I agree to follow this project's [Code of Conduct](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/CODE_OF_CONDUCT.md).
- [x] I checked the [current issues](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/issues) for duplicate problems.
- [x] I have gone through project [README](https://github.com/ZeroOctave/ZeroOctave-Javascript-Projects/blob/main/README.md).

**Comment by hirentimbadiya** [comment]
hey can i work on this issue of correcting typos in Gym Website and Add meaningful text at some places.
